// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
#include "embedded_models.h"

extern "C" {
extern const unsigned char _emb_pte_portable__adaptive_avg_pool2d_start[];
extern const unsigned char _emb_pte_portable__adaptive_avg_pool2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__conj_physical_start[];
extern const unsigned char _emb_pte_portable__conj_physical_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__abs_start[];
extern const unsigned char _emb_pte_portable__abs_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__acos_start[];
extern const unsigned char _emb_pte_portable__acos_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__acosh_start[];
extern const unsigned char _emb_pte_portable__acosh_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__add_start[];
extern const unsigned char _emb_pte_portable__add_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__addmm_start[];
extern const unsigned char _emb_pte_portable__addmm_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__alias_copy_start[];
extern const unsigned char _emb_pte_portable__alias_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__amax_start[];
extern const unsigned char _emb_pte_portable__amax_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__amin_start[];
extern const unsigned char _emb_pte_portable__amin_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__any_start[];
extern const unsigned char _emb_pte_portable__any_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__argmax_start[];
extern const unsigned char _emb_pte_portable__argmax_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__argmin_start[];
extern const unsigned char _emb_pte_portable__argmin_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__as_strided_copy_start[];
extern const unsigned char _emb_pte_portable__as_strided_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__asin_start[];
extern const unsigned char _emb_pte_portable__asin_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__asinh_start[];
extern const unsigned char _emb_pte_portable__asinh_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__atan_start[];
extern const unsigned char _emb_pte_portable__atan_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__atan2_start[];
extern const unsigned char _emb_pte_portable__atan2_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__atanh_start[];
extern const unsigned char _emb_pte_portable__atanh_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__avg_pool2d_start[];
extern const unsigned char _emb_pte_portable__avg_pool2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bitwise_and_start[];
extern const unsigned char _emb_pte_portable__bitwise_and_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bitwise_left_shift_start[];
extern const unsigned char _emb_pte_portable__bitwise_left_shift_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bitwise_not_start[];
extern const unsigned char _emb_pte_portable__bitwise_not_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bitwise_or_start[];
extern const unsigned char _emb_pte_portable__bitwise_or_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bitwise_right_shift_start[];
extern const unsigned char _emb_pte_portable__bitwise_right_shift_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bitwise_xor_start[];
extern const unsigned char _emb_pte_portable__bitwise_xor_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bmm_start[];
extern const unsigned char _emb_pte_portable__bmm_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__cat_start[];
extern const unsigned char _emb_pte_portable__cat_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__ceil_start[];
extern const unsigned char _emb_pte_portable__ceil_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__clamp_start[];
extern const unsigned char _emb_pte_portable__clamp_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__clone_start[];
extern const unsigned char _emb_pte_portable__clone_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__constant_pad_nd_start[];
extern const unsigned char _emb_pte_portable__constant_pad_nd_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__convolution_start[];
extern const unsigned char _emb_pte_portable__convolution_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__copy_start[];
extern const unsigned char _emb_pte_portable__copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__cos_start[];
extern const unsigned char _emb_pte_portable__cos_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__cosh_start[];
extern const unsigned char _emb_pte_portable__cosh_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__cumsum_start[];
extern const unsigned char _emb_pte_portable__cumsum_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__detach_copy_start[];
extern const unsigned char _emb_pte_portable__detach_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__diagonal_copy_start[];
extern const unsigned char _emb_pte_portable__diagonal_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__div_start[];
extern const unsigned char _emb_pte_portable__div_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__elu_start[];
extern const unsigned char _emb_pte_portable__elu_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__embedding_start[];
extern const unsigned char _emb_pte_portable__embedding_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__eq_start[];
extern const unsigned char _emb_pte_portable__eq_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__erf_start[];
extern const unsigned char _emb_pte_portable__erf_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__exp_start[];
extern const unsigned char _emb_pte_portable__exp_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__expand_copy_start[];
extern const unsigned char _emb_pte_portable__expand_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__expm1_start[];
extern const unsigned char _emb_pte_portable__expm1_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__fill_start[];
extern const unsigned char _emb_pte_portable__fill_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__flip_start[];
extern const unsigned char _emb_pte_portable__flip_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__floor_start[];
extern const unsigned char _emb_pte_portable__floor_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__floor_divide_start[];
extern const unsigned char _emb_pte_portable__floor_divide_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__fmod_start[];
extern const unsigned char _emb_pte_portable__fmod_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__full_like_start[];
extern const unsigned char _emb_pte_portable__full_like_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__gather_start[];
extern const unsigned char _emb_pte_portable__gather_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__ge_start[];
extern const unsigned char _emb_pte_portable__ge_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__gelu_start[];
extern const unsigned char _emb_pte_portable__gelu_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__glu_start[];
extern const unsigned char _emb_pte_portable__glu_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__gt_start[];
extern const unsigned char _emb_pte_portable__gt_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__hardtanh_start[];
extern const unsigned char _emb_pte_portable__hardtanh_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__index_start[];
extern const unsigned char _emb_pte_portable__index_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__index_put_start[];
extern const unsigned char _emb_pte_portable__index_put_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__index_select_start[];
extern const unsigned char _emb_pte_portable__index_select_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__isinf_start[];
extern const unsigned char _emb_pte_portable__isinf_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__isnan_start[];
extern const unsigned char _emb_pte_portable__isnan_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__le_start[];
extern const unsigned char _emb_pte_portable__le_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__leaky_relu_start[];
extern const unsigned char _emb_pte_portable__leaky_relu_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__lift_fresh_copy_start[];
extern const unsigned char _emb_pte_portable__lift_fresh_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__log_start[];
extern const unsigned char _emb_pte_portable__log_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__log10_start[];
extern const unsigned char _emb_pte_portable__log10_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__log1p_start[];
extern const unsigned char _emb_pte_portable__log1p_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__log2_start[];
extern const unsigned char _emb_pte_portable__log2_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__log_softmax_start[];
extern const unsigned char _emb_pte_portable__log_softmax_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__logical_and_start[];
extern const unsigned char _emb_pte_portable__logical_and_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__logical_not_start[];
extern const unsigned char _emb_pte_portable__logical_not_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__logical_or_start[];
extern const unsigned char _emb_pte_portable__logical_or_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__logical_xor_start[];
extern const unsigned char _emb_pte_portable__logical_xor_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__logit_start[];
extern const unsigned char _emb_pte_portable__logit_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__lt_start[];
extern const unsigned char _emb_pte_portable__lt_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__masked_fill_start[];
extern const unsigned char _emb_pte_portable__masked_fill_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__masked_scatter_start[];
extern const unsigned char _emb_pte_portable__masked_scatter_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__max_start[];
extern const unsigned char _emb_pte_portable__max_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__max_pool2d_with_indices_start[];
extern const unsigned char _emb_pte_portable__max_pool2d_with_indices_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__maximum_start[];
extern const unsigned char _emb_pte_portable__maximum_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__mean_start[];
extern const unsigned char _emb_pte_portable__mean_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__min_start[];
extern const unsigned char _emb_pte_portable__min_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__minimum_start[];
extern const unsigned char _emb_pte_portable__minimum_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__mm_start[];
extern const unsigned char _emb_pte_portable__mm_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__mul_start[];
extern const unsigned char _emb_pte_portable__mul_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__narrow_copy_start[];
extern const unsigned char _emb_pte_portable__narrow_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__native_batch_norm_start[];
extern const unsigned char _emb_pte_portable__native_batch_norm_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__native_group_norm_start[];
extern const unsigned char _emb_pte_portable__native_group_norm_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__native_layer_norm_start[];
extern const unsigned char _emb_pte_portable__native_layer_norm_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__ne_start[];
extern const unsigned char _emb_pte_portable__ne_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__neg_start[];
extern const unsigned char _emb_pte_portable__neg_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__permute_copy_start[];
extern const unsigned char _emb_pte_portable__permute_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__pixel_shuffle_start[];
extern const unsigned char _emb_pte_portable__pixel_shuffle_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__pixel_unshuffle_start[];
extern const unsigned char _emb_pte_portable__pixel_unshuffle_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__pow_start[];
extern const unsigned char _emb_pte_portable__pow_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__prod_start[];
extern const unsigned char _emb_pte_portable__prod_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__reciprocal_start[];
extern const unsigned char _emb_pte_portable__reciprocal_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__reflection_pad1d_start[];
extern const unsigned char _emb_pte_portable__reflection_pad1d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__reflection_pad2d_start[];
extern const unsigned char _emb_pte_portable__reflection_pad2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__reflection_pad3d_start[];
extern const unsigned char _emb_pte_portable__reflection_pad3d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__relu_start[];
extern const unsigned char _emb_pte_portable__relu_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__remainder_start[];
extern const unsigned char _emb_pte_portable__remainder_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__repeat_start[];
extern const unsigned char _emb_pte_portable__repeat_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__repeat_interleave_start[];
extern const unsigned char _emb_pte_portable__repeat_interleave_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__replication_pad1d_start[];
extern const unsigned char _emb_pte_portable__replication_pad1d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__replication_pad2d_start[];
extern const unsigned char _emb_pte_portable__replication_pad2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__replication_pad3d_start[];
extern const unsigned char _emb_pte_portable__replication_pad3d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__roll_start[];
extern const unsigned char _emb_pte_portable__roll_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__round_start[];
extern const unsigned char _emb_pte_portable__round_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__rsqrt_start[];
extern const unsigned char _emb_pte_portable__rsqrt_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__rsub_start[];
extern const unsigned char _emb_pte_portable__rsub_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__scatter_start[];
extern const unsigned char _emb_pte_portable__scatter_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__scatter_add_start[];
extern const unsigned char _emb_pte_portable__scatter_add_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__select_copy_start[];
extern const unsigned char _emb_pte_portable__select_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__select_scatter_start[];
extern const unsigned char _emb_pte_portable__select_scatter_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__sigmoid_start[];
extern const unsigned char _emb_pte_portable__sigmoid_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__sign_start[];
extern const unsigned char _emb_pte_portable__sign_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__sin_start[];
extern const unsigned char _emb_pte_portable__sin_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__sinh_start[];
extern const unsigned char _emb_pte_portable__sinh_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__slice_copy_start[];
extern const unsigned char _emb_pte_portable__slice_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__slice_scatter_start[];
extern const unsigned char _emb_pte_portable__slice_scatter_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__softmax_start[];
extern const unsigned char _emb_pte_portable__softmax_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__split_copy_start[];
extern const unsigned char _emb_pte_portable__split_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__split_with_sizes_copy_start[];
extern const unsigned char _emb_pte_portable__split_with_sizes_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__sqrt_start[];
extern const unsigned char _emb_pte_portable__sqrt_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__squeeze_copy_start[];
extern const unsigned char _emb_pte_portable__squeeze_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__stack_start[];
extern const unsigned char _emb_pte_portable__stack_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__sub_start[];
extern const unsigned char _emb_pte_portable__sub_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__sum_start[];
extern const unsigned char _emb_pte_portable__sum_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__t_copy_start[];
extern const unsigned char _emb_pte_portable__t_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__tan_start[];
extern const unsigned char _emb_pte_portable__tan_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__tanh_start[];
extern const unsigned char _emb_pte_portable__tanh_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__to_copy_start[];
extern const unsigned char _emb_pte_portable__to_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__topk_start[];
extern const unsigned char _emb_pte_portable__topk_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__transpose_copy_start[];
extern const unsigned char _emb_pte_portable__transpose_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__tril_start[];
extern const unsigned char _emb_pte_portable__tril_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__trunc_start[];
extern const unsigned char _emb_pte_portable__trunc_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__unbind_copy_start[];
extern const unsigned char _emb_pte_portable__unbind_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__unfold_copy_start[];
extern const unsigned char _emb_pte_portable__unfold_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__unsqueeze_copy_start[];
extern const unsigned char _emb_pte_portable__unsqueeze_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__upsample_bilinear2d_start[];
extern const unsigned char _emb_pte_portable__upsample_bilinear2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__upsample_nearest2d_start[];
extern const unsigned char _emb_pte_portable__upsample_nearest2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__var_start[];
extern const unsigned char _emb_pte_portable__var_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__var_mean_start[];
extern const unsigned char _emb_pte_portable__var_mean_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__view_copy_start[];
extern const unsigned char _emb_pte_portable__view_copy_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__where_start[];
extern const unsigned char _emb_pte_portable__where_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__dequantize_per_tensor_start[];
extern const unsigned char _emb_pte_cortex_m__dequantize_per_tensor_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__maximum_start[];
extern const unsigned char _emb_pte_cortex_m__maximum_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__minimum_start[];
extern const unsigned char _emb_pte_cortex_m__minimum_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__pad_start[];
extern const unsigned char _emb_pte_cortex_m__pad_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantize_per_tensor_start[];
extern const unsigned char _emb_pte_cortex_m__quantize_per_tensor_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_add_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_add_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_avg_pool2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_avg_pool2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_batch_matmul_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_batch_matmul_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_conv2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_conv2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_depthwise_conv2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_depthwise_conv2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_linear_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_linear_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_max_pool2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_max_pool2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_mul_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_mul_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_transpose_conv2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_transpose_conv2d_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__softmax_start[];
extern const unsigned char _emb_pte_cortex_m__softmax_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__transpose_start[];
extern const unsigned char _emb_pte_cortex_m__transpose_end[];
}  // extern "C"


const EmbeddedModel g_embedded_models[] = {
    { "adaptive_avg_pool2d", "portable__adaptive_avg_pool2d",
      _emb_pte_portable__adaptive_avg_pool2d_start, static_cast<std::size_t>(_emb_pte_portable__adaptive_avg_pool2d_end - _emb_pte_portable__adaptive_avg_pool2d_start),
    },
    { "conj_physical", "portable__conj_physical",
      _emb_pte_portable__conj_physical_start, static_cast<std::size_t>(_emb_pte_portable__conj_physical_end - _emb_pte_portable__conj_physical_start),
    },
    { "abs", "portable__abs",
      _emb_pte_portable__abs_start, static_cast<std::size_t>(_emb_pte_portable__abs_end - _emb_pte_portable__abs_start),
    },
    { "acos", "portable__acos",
      _emb_pte_portable__acos_start, static_cast<std::size_t>(_emb_pte_portable__acos_end - _emb_pte_portable__acos_start),
    },
    { "acosh", "portable__acosh",
      _emb_pte_portable__acosh_start, static_cast<std::size_t>(_emb_pte_portable__acosh_end - _emb_pte_portable__acosh_start),
    },
    { "add", "portable__add",
      _emb_pte_portable__add_start, static_cast<std::size_t>(_emb_pte_portable__add_end - _emb_pte_portable__add_start),
    },
    { "addmm", "portable__addmm",
      _emb_pte_portable__addmm_start, static_cast<std::size_t>(_emb_pte_portable__addmm_end - _emb_pte_portable__addmm_start),
    },
    { "alias_copy", "portable__alias_copy",
      _emb_pte_portable__alias_copy_start, static_cast<std::size_t>(_emb_pte_portable__alias_copy_end - _emb_pte_portable__alias_copy_start),
    },
    { "amax", "portable__amax",
      _emb_pte_portable__amax_start, static_cast<std::size_t>(_emb_pte_portable__amax_end - _emb_pte_portable__amax_start),
    },
    { "amin", "portable__amin",
      _emb_pte_portable__amin_start, static_cast<std::size_t>(_emb_pte_portable__amin_end - _emb_pte_portable__amin_start),
    },
    { "any", "portable__any",
      _emb_pte_portable__any_start, static_cast<std::size_t>(_emb_pte_portable__any_end - _emb_pte_portable__any_start),
    },
    { "argmax", "portable__argmax",
      _emb_pte_portable__argmax_start, static_cast<std::size_t>(_emb_pte_portable__argmax_end - _emb_pte_portable__argmax_start),
    },
    { "argmin", "portable__argmin",
      _emb_pte_portable__argmin_start, static_cast<std::size_t>(_emb_pte_portable__argmin_end - _emb_pte_portable__argmin_start),
    },
    { "as_strided_copy", "portable__as_strided_copy",
      _emb_pte_portable__as_strided_copy_start, static_cast<std::size_t>(_emb_pte_portable__as_strided_copy_end - _emb_pte_portable__as_strided_copy_start),
    },
    { "asin", "portable__asin",
      _emb_pte_portable__asin_start, static_cast<std::size_t>(_emb_pte_portable__asin_end - _emb_pte_portable__asin_start),
    },
    { "asinh", "portable__asinh",
      _emb_pte_portable__asinh_start, static_cast<std::size_t>(_emb_pte_portable__asinh_end - _emb_pte_portable__asinh_start),
    },
    { "atan", "portable__atan",
      _emb_pte_portable__atan_start, static_cast<std::size_t>(_emb_pte_portable__atan_end - _emb_pte_portable__atan_start),
    },
    { "atan2", "portable__atan2",
      _emb_pte_portable__atan2_start, static_cast<std::size_t>(_emb_pte_portable__atan2_end - _emb_pte_portable__atan2_start),
    },
    { "atanh", "portable__atanh",
      _emb_pte_portable__atanh_start, static_cast<std::size_t>(_emb_pte_portable__atanh_end - _emb_pte_portable__atanh_start),
    },
    { "avg_pool2d", "portable__avg_pool2d",
      _emb_pte_portable__avg_pool2d_start, static_cast<std::size_t>(_emb_pte_portable__avg_pool2d_end - _emb_pte_portable__avg_pool2d_start),
    },
    { "bitwise_and", "portable__bitwise_and",
      _emb_pte_portable__bitwise_and_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_and_end - _emb_pte_portable__bitwise_and_start),
    },
    { "bitwise_left_shift", "portable__bitwise_left_shift",
      _emb_pte_portable__bitwise_left_shift_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_left_shift_end - _emb_pte_portable__bitwise_left_shift_start),
    },
    { "bitwise_not", "portable__bitwise_not",
      _emb_pte_portable__bitwise_not_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_not_end - _emb_pte_portable__bitwise_not_start),
    },
    { "bitwise_or", "portable__bitwise_or",
      _emb_pte_portable__bitwise_or_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_or_end - _emb_pte_portable__bitwise_or_start),
    },
    { "bitwise_right_shift", "portable__bitwise_right_shift",
      _emb_pte_portable__bitwise_right_shift_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_right_shift_end - _emb_pte_portable__bitwise_right_shift_start),
    },
    { "bitwise_xor", "portable__bitwise_xor",
      _emb_pte_portable__bitwise_xor_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_xor_end - _emb_pte_portable__bitwise_xor_start),
    },
    { "bmm", "portable__bmm",
      _emb_pte_portable__bmm_start, static_cast<std::size_t>(_emb_pte_portable__bmm_end - _emb_pte_portable__bmm_start),
    },
    { "cat", "portable__cat",
      _emb_pte_portable__cat_start, static_cast<std::size_t>(_emb_pte_portable__cat_end - _emb_pte_portable__cat_start),
    },
    { "ceil", "portable__ceil",
      _emb_pte_portable__ceil_start, static_cast<std::size_t>(_emb_pte_portable__ceil_end - _emb_pte_portable__ceil_start),
    },
    { "clamp", "portable__clamp",
      _emb_pte_portable__clamp_start, static_cast<std::size_t>(_emb_pte_portable__clamp_end - _emb_pte_portable__clamp_start),
    },
    { "clone", "portable__clone",
      _emb_pte_portable__clone_start, static_cast<std::size_t>(_emb_pte_portable__clone_end - _emb_pte_portable__clone_start),
    },
    { "constant_pad_nd", "portable__constant_pad_nd",
      _emb_pte_portable__constant_pad_nd_start, static_cast<std::size_t>(_emb_pte_portable__constant_pad_nd_end - _emb_pte_portable__constant_pad_nd_start),
    },
    { "convolution", "portable__convolution",
      _emb_pte_portable__convolution_start, static_cast<std::size_t>(_emb_pte_portable__convolution_end - _emb_pte_portable__convolution_start),
    },
    { "copy", "portable__copy",
      _emb_pte_portable__copy_start, static_cast<std::size_t>(_emb_pte_portable__copy_end - _emb_pte_portable__copy_start),
    },
    { "cos", "portable__cos",
      _emb_pte_portable__cos_start, static_cast<std::size_t>(_emb_pte_portable__cos_end - _emb_pte_portable__cos_start),
    },
    { "cosh", "portable__cosh",
      _emb_pte_portable__cosh_start, static_cast<std::size_t>(_emb_pte_portable__cosh_end - _emb_pte_portable__cosh_start),
    },
    { "cumsum", "portable__cumsum",
      _emb_pte_portable__cumsum_start, static_cast<std::size_t>(_emb_pte_portable__cumsum_end - _emb_pte_portable__cumsum_start),
    },
    { "detach_copy", "portable__detach_copy",
      _emb_pte_portable__detach_copy_start, static_cast<std::size_t>(_emb_pte_portable__detach_copy_end - _emb_pte_portable__detach_copy_start),
    },
    { "diagonal_copy", "portable__diagonal_copy",
      _emb_pte_portable__diagonal_copy_start, static_cast<std::size_t>(_emb_pte_portable__diagonal_copy_end - _emb_pte_portable__diagonal_copy_start),
    },
    { "div", "portable__div",
      _emb_pte_portable__div_start, static_cast<std::size_t>(_emb_pte_portable__div_end - _emb_pte_portable__div_start),
    },
    { "elu", "portable__elu",
      _emb_pte_portable__elu_start, static_cast<std::size_t>(_emb_pte_portable__elu_end - _emb_pte_portable__elu_start),
    },
    { "embedding", "portable__embedding",
      _emb_pte_portable__embedding_start, static_cast<std::size_t>(_emb_pte_portable__embedding_end - _emb_pte_portable__embedding_start),
    },
    { "eq", "portable__eq",
      _emb_pte_portable__eq_start, static_cast<std::size_t>(_emb_pte_portable__eq_end - _emb_pte_portable__eq_start),
    },
    { "erf", "portable__erf",
      _emb_pte_portable__erf_start, static_cast<std::size_t>(_emb_pte_portable__erf_end - _emb_pte_portable__erf_start),
    },
    { "exp", "portable__exp",
      _emb_pte_portable__exp_start, static_cast<std::size_t>(_emb_pte_portable__exp_end - _emb_pte_portable__exp_start),
    },
    { "expand_copy", "portable__expand_copy",
      _emb_pte_portable__expand_copy_start, static_cast<std::size_t>(_emb_pte_portable__expand_copy_end - _emb_pte_portable__expand_copy_start),
    },
    { "expm1", "portable__expm1",
      _emb_pte_portable__expm1_start, static_cast<std::size_t>(_emb_pte_portable__expm1_end - _emb_pte_portable__expm1_start),
    },
    { "fill", "portable__fill",
      _emb_pte_portable__fill_start, static_cast<std::size_t>(_emb_pte_portable__fill_end - _emb_pte_portable__fill_start),
    },
    { "flip", "portable__flip",
      _emb_pte_portable__flip_start, static_cast<std::size_t>(_emb_pte_portable__flip_end - _emb_pte_portable__flip_start),
    },
    { "floor", "portable__floor",
      _emb_pte_portable__floor_start, static_cast<std::size_t>(_emb_pte_portable__floor_end - _emb_pte_portable__floor_start),
    },
    { "floor_divide", "portable__floor_divide",
      _emb_pte_portable__floor_divide_start, static_cast<std::size_t>(_emb_pte_portable__floor_divide_end - _emb_pte_portable__floor_divide_start),
    },
    { "fmod", "portable__fmod",
      _emb_pte_portable__fmod_start, static_cast<std::size_t>(_emb_pte_portable__fmod_end - _emb_pte_portable__fmod_start),
    },
    { "full_like", "portable__full_like",
      _emb_pte_portable__full_like_start, static_cast<std::size_t>(_emb_pte_portable__full_like_end - _emb_pte_portable__full_like_start),
    },
    { "gather", "portable__gather",
      _emb_pte_portable__gather_start, static_cast<std::size_t>(_emb_pte_portable__gather_end - _emb_pte_portable__gather_start),
    },
    { "ge", "portable__ge",
      _emb_pte_portable__ge_start, static_cast<std::size_t>(_emb_pte_portable__ge_end - _emb_pte_portable__ge_start),
    },
    { "gelu", "portable__gelu",
      _emb_pte_portable__gelu_start, static_cast<std::size_t>(_emb_pte_portable__gelu_end - _emb_pte_portable__gelu_start),
    },
    { "glu", "portable__glu",
      _emb_pte_portable__glu_start, static_cast<std::size_t>(_emb_pte_portable__glu_end - _emb_pte_portable__glu_start),
    },
    { "gt", "portable__gt",
      _emb_pte_portable__gt_start, static_cast<std::size_t>(_emb_pte_portable__gt_end - _emb_pte_portable__gt_start),
    },
    { "hardtanh", "portable__hardtanh",
      _emb_pte_portable__hardtanh_start, static_cast<std::size_t>(_emb_pte_portable__hardtanh_end - _emb_pte_portable__hardtanh_start),
    },
    { "index", "portable__index",
      _emb_pte_portable__index_start, static_cast<std::size_t>(_emb_pte_portable__index_end - _emb_pte_portable__index_start),
    },
    { "index_put", "portable__index_put",
      _emb_pte_portable__index_put_start, static_cast<std::size_t>(_emb_pte_portable__index_put_end - _emb_pte_portable__index_put_start),
    },
    { "index_select", "portable__index_select",
      _emb_pte_portable__index_select_start, static_cast<std::size_t>(_emb_pte_portable__index_select_end - _emb_pte_portable__index_select_start),
    },
    { "isinf", "portable__isinf",
      _emb_pte_portable__isinf_start, static_cast<std::size_t>(_emb_pte_portable__isinf_end - _emb_pte_portable__isinf_start),
    },
    { "isnan", "portable__isnan",
      _emb_pte_portable__isnan_start, static_cast<std::size_t>(_emb_pte_portable__isnan_end - _emb_pte_portable__isnan_start),
    },
    { "le", "portable__le",
      _emb_pte_portable__le_start, static_cast<std::size_t>(_emb_pte_portable__le_end - _emb_pte_portable__le_start),
    },
    { "leaky_relu", "portable__leaky_relu",
      _emb_pte_portable__leaky_relu_start, static_cast<std::size_t>(_emb_pte_portable__leaky_relu_end - _emb_pte_portable__leaky_relu_start),
    },
    { "lift_fresh_copy", "portable__lift_fresh_copy",
      _emb_pte_portable__lift_fresh_copy_start, static_cast<std::size_t>(_emb_pte_portable__lift_fresh_copy_end - _emb_pte_portable__lift_fresh_copy_start),
    },
    { "log", "portable__log",
      _emb_pte_portable__log_start, static_cast<std::size_t>(_emb_pte_portable__log_end - _emb_pte_portable__log_start),
    },
    { "log10", "portable__log10",
      _emb_pte_portable__log10_start, static_cast<std::size_t>(_emb_pte_portable__log10_end - _emb_pte_portable__log10_start),
    },
    { "log1p", "portable__log1p",
      _emb_pte_portable__log1p_start, static_cast<std::size_t>(_emb_pte_portable__log1p_end - _emb_pte_portable__log1p_start),
    },
    { "log2", "portable__log2",
      _emb_pte_portable__log2_start, static_cast<std::size_t>(_emb_pte_portable__log2_end - _emb_pte_portable__log2_start),
    },
    { "log_softmax", "portable__log_softmax",
      _emb_pte_portable__log_softmax_start, static_cast<std::size_t>(_emb_pte_portable__log_softmax_end - _emb_pte_portable__log_softmax_start),
    },
    { "logical_and", "portable__logical_and",
      _emb_pte_portable__logical_and_start, static_cast<std::size_t>(_emb_pte_portable__logical_and_end - _emb_pte_portable__logical_and_start),
    },
    { "logical_not", "portable__logical_not",
      _emb_pte_portable__logical_not_start, static_cast<std::size_t>(_emb_pte_portable__logical_not_end - _emb_pte_portable__logical_not_start),
    },
    { "logical_or", "portable__logical_or",
      _emb_pte_portable__logical_or_start, static_cast<std::size_t>(_emb_pte_portable__logical_or_end - _emb_pte_portable__logical_or_start),
    },
    { "logical_xor", "portable__logical_xor",
      _emb_pte_portable__logical_xor_start, static_cast<std::size_t>(_emb_pte_portable__logical_xor_end - _emb_pte_portable__logical_xor_start),
    },
    { "logit", "portable__logit",
      _emb_pte_portable__logit_start, static_cast<std::size_t>(_emb_pte_portable__logit_end - _emb_pte_portable__logit_start),
    },
    { "lt", "portable__lt",
      _emb_pte_portable__lt_start, static_cast<std::size_t>(_emb_pte_portable__lt_end - _emb_pte_portable__lt_start),
    },
    { "masked_fill", "portable__masked_fill",
      _emb_pte_portable__masked_fill_start, static_cast<std::size_t>(_emb_pte_portable__masked_fill_end - _emb_pte_portable__masked_fill_start),
    },
    { "masked_scatter", "portable__masked_scatter",
      _emb_pte_portable__masked_scatter_start, static_cast<std::size_t>(_emb_pte_portable__masked_scatter_end - _emb_pte_portable__masked_scatter_start),
    },
    { "max", "portable__max",
      _emb_pte_portable__max_start, static_cast<std::size_t>(_emb_pte_portable__max_end - _emb_pte_portable__max_start),
    },
    { "max_pool2d_with_indices", "portable__max_pool2d_with_indices",
      _emb_pte_portable__max_pool2d_with_indices_start, static_cast<std::size_t>(_emb_pte_portable__max_pool2d_with_indices_end - _emb_pte_portable__max_pool2d_with_indices_start),
    },
    { "maximum", "portable__maximum",
      _emb_pte_portable__maximum_start, static_cast<std::size_t>(_emb_pte_portable__maximum_end - _emb_pte_portable__maximum_start),
    },
    { "mean", "portable__mean",
      _emb_pte_portable__mean_start, static_cast<std::size_t>(_emb_pte_portable__mean_end - _emb_pte_portable__mean_start),
    },
    { "min", "portable__min",
      _emb_pte_portable__min_start, static_cast<std::size_t>(_emb_pte_portable__min_end - _emb_pte_portable__min_start),
    },
    { "minimum", "portable__minimum",
      _emb_pte_portable__minimum_start, static_cast<std::size_t>(_emb_pte_portable__minimum_end - _emb_pte_portable__minimum_start),
    },
    { "mm", "portable__mm",
      _emb_pte_portable__mm_start, static_cast<std::size_t>(_emb_pte_portable__mm_end - _emb_pte_portable__mm_start),
    },
    { "mul", "portable__mul",
      _emb_pte_portable__mul_start, static_cast<std::size_t>(_emb_pte_portable__mul_end - _emb_pte_portable__mul_start),
    },
    { "narrow_copy", "portable__narrow_copy",
      _emb_pte_portable__narrow_copy_start, static_cast<std::size_t>(_emb_pte_portable__narrow_copy_end - _emb_pte_portable__narrow_copy_start),
    },
    { "native_batch_norm", "portable__native_batch_norm",
      _emb_pte_portable__native_batch_norm_start, static_cast<std::size_t>(_emb_pte_portable__native_batch_norm_end - _emb_pte_portable__native_batch_norm_start),
    },
    { "native_group_norm", "portable__native_group_norm",
      _emb_pte_portable__native_group_norm_start, static_cast<std::size_t>(_emb_pte_portable__native_group_norm_end - _emb_pte_portable__native_group_norm_start),
    },
    { "native_layer_norm", "portable__native_layer_norm",
      _emb_pte_portable__native_layer_norm_start, static_cast<std::size_t>(_emb_pte_portable__native_layer_norm_end - _emb_pte_portable__native_layer_norm_start),
    },
    { "ne", "portable__ne",
      _emb_pte_portable__ne_start, static_cast<std::size_t>(_emb_pte_portable__ne_end - _emb_pte_portable__ne_start),
    },
    { "neg", "portable__neg",
      _emb_pte_portable__neg_start, static_cast<std::size_t>(_emb_pte_portable__neg_end - _emb_pte_portable__neg_start),
    },
    { "permute_copy", "portable__permute_copy",
      _emb_pte_portable__permute_copy_start, static_cast<std::size_t>(_emb_pte_portable__permute_copy_end - _emb_pte_portable__permute_copy_start),
    },
    { "pixel_shuffle", "portable__pixel_shuffle",
      _emb_pte_portable__pixel_shuffle_start, static_cast<std::size_t>(_emb_pte_portable__pixel_shuffle_end - _emb_pte_portable__pixel_shuffle_start),
    },
    { "pixel_unshuffle", "portable__pixel_unshuffle",
      _emb_pte_portable__pixel_unshuffle_start, static_cast<std::size_t>(_emb_pte_portable__pixel_unshuffle_end - _emb_pte_portable__pixel_unshuffle_start),
    },
    { "pow", "portable__pow",
      _emb_pte_portable__pow_start, static_cast<std::size_t>(_emb_pte_portable__pow_end - _emb_pte_portable__pow_start),
    },
    { "prod", "portable__prod",
      _emb_pte_portable__prod_start, static_cast<std::size_t>(_emb_pte_portable__prod_end - _emb_pte_portable__prod_start),
    },
    { "reciprocal", "portable__reciprocal",
      _emb_pte_portable__reciprocal_start, static_cast<std::size_t>(_emb_pte_portable__reciprocal_end - _emb_pte_portable__reciprocal_start),
    },
    { "reflection_pad1d", "portable__reflection_pad1d",
      _emb_pte_portable__reflection_pad1d_start, static_cast<std::size_t>(_emb_pte_portable__reflection_pad1d_end - _emb_pte_portable__reflection_pad1d_start),
    },
    { "reflection_pad2d", "portable__reflection_pad2d",
      _emb_pte_portable__reflection_pad2d_start, static_cast<std::size_t>(_emb_pte_portable__reflection_pad2d_end - _emb_pte_portable__reflection_pad2d_start),
    },
    { "reflection_pad3d", "portable__reflection_pad3d",
      _emb_pte_portable__reflection_pad3d_start, static_cast<std::size_t>(_emb_pte_portable__reflection_pad3d_end - _emb_pte_portable__reflection_pad3d_start),
    },
    { "relu", "portable__relu",
      _emb_pte_portable__relu_start, static_cast<std::size_t>(_emb_pte_portable__relu_end - _emb_pte_portable__relu_start),
    },
    { "remainder", "portable__remainder",
      _emb_pte_portable__remainder_start, static_cast<std::size_t>(_emb_pte_portable__remainder_end - _emb_pte_portable__remainder_start),
    },
    { "repeat", "portable__repeat",
      _emb_pte_portable__repeat_start, static_cast<std::size_t>(_emb_pte_portable__repeat_end - _emb_pte_portable__repeat_start),
    },
    { "repeat_interleave", "portable__repeat_interleave",
      _emb_pte_portable__repeat_interleave_start, static_cast<std::size_t>(_emb_pte_portable__repeat_interleave_end - _emb_pte_portable__repeat_interleave_start),
    },
    { "replication_pad1d", "portable__replication_pad1d",
      _emb_pte_portable__replication_pad1d_start, static_cast<std::size_t>(_emb_pte_portable__replication_pad1d_end - _emb_pte_portable__replication_pad1d_start),
    },
    { "replication_pad2d", "portable__replication_pad2d",
      _emb_pte_portable__replication_pad2d_start, static_cast<std::size_t>(_emb_pte_portable__replication_pad2d_end - _emb_pte_portable__replication_pad2d_start),
    },
    { "replication_pad3d", "portable__replication_pad3d",
      _emb_pte_portable__replication_pad3d_start, static_cast<std::size_t>(_emb_pte_portable__replication_pad3d_end - _emb_pte_portable__replication_pad3d_start),
    },
    { "roll", "portable__roll",
      _emb_pte_portable__roll_start, static_cast<std::size_t>(_emb_pte_portable__roll_end - _emb_pte_portable__roll_start),
    },
    { "round", "portable__round",
      _emb_pte_portable__round_start, static_cast<std::size_t>(_emb_pte_portable__round_end - _emb_pte_portable__round_start),
    },
    { "rsqrt", "portable__rsqrt",
      _emb_pte_portable__rsqrt_start, static_cast<std::size_t>(_emb_pte_portable__rsqrt_end - _emb_pte_portable__rsqrt_start),
    },
    { "rsub", "portable__rsub",
      _emb_pte_portable__rsub_start, static_cast<std::size_t>(_emb_pte_portable__rsub_end - _emb_pte_portable__rsub_start),
    },
    { "scatter", "portable__scatter",
      _emb_pte_portable__scatter_start, static_cast<std::size_t>(_emb_pte_portable__scatter_end - _emb_pte_portable__scatter_start),
    },
    { "scatter_add", "portable__scatter_add",
      _emb_pte_portable__scatter_add_start, static_cast<std::size_t>(_emb_pte_portable__scatter_add_end - _emb_pte_portable__scatter_add_start),
    },
    { "select_copy", "portable__select_copy",
      _emb_pte_portable__select_copy_start, static_cast<std::size_t>(_emb_pte_portable__select_copy_end - _emb_pte_portable__select_copy_start),
    },
    { "select_scatter", "portable__select_scatter",
      _emb_pte_portable__select_scatter_start, static_cast<std::size_t>(_emb_pte_portable__select_scatter_end - _emb_pte_portable__select_scatter_start),
    },
    { "sigmoid", "portable__sigmoid",
      _emb_pte_portable__sigmoid_start, static_cast<std::size_t>(_emb_pte_portable__sigmoid_end - _emb_pte_portable__sigmoid_start),
    },
    { "sign", "portable__sign",
      _emb_pte_portable__sign_start, static_cast<std::size_t>(_emb_pte_portable__sign_end - _emb_pte_portable__sign_start),
    },
    { "sin", "portable__sin",
      _emb_pte_portable__sin_start, static_cast<std::size_t>(_emb_pte_portable__sin_end - _emb_pte_portable__sin_start),
    },
    { "sinh", "portable__sinh",
      _emb_pte_portable__sinh_start, static_cast<std::size_t>(_emb_pte_portable__sinh_end - _emb_pte_portable__sinh_start),
    },
    { "slice_copy", "portable__slice_copy",
      _emb_pte_portable__slice_copy_start, static_cast<std::size_t>(_emb_pte_portable__slice_copy_end - _emb_pte_portable__slice_copy_start),
    },
    { "slice_scatter", "portable__slice_scatter",
      _emb_pte_portable__slice_scatter_start, static_cast<std::size_t>(_emb_pte_portable__slice_scatter_end - _emb_pte_portable__slice_scatter_start),
    },
    { "softmax", "portable__softmax",
      _emb_pte_portable__softmax_start, static_cast<std::size_t>(_emb_pte_portable__softmax_end - _emb_pte_portable__softmax_start),
    },
    { "split_copy", "portable__split_copy",
      _emb_pte_portable__split_copy_start, static_cast<std::size_t>(_emb_pte_portable__split_copy_end - _emb_pte_portable__split_copy_start),
    },
    { "split_with_sizes_copy", "portable__split_with_sizes_copy",
      _emb_pte_portable__split_with_sizes_copy_start, static_cast<std::size_t>(_emb_pte_portable__split_with_sizes_copy_end - _emb_pte_portable__split_with_sizes_copy_start),
    },
    { "sqrt", "portable__sqrt",
      _emb_pte_portable__sqrt_start, static_cast<std::size_t>(_emb_pte_portable__sqrt_end - _emb_pte_portable__sqrt_start),
    },
    { "squeeze_copy", "portable__squeeze_copy",
      _emb_pte_portable__squeeze_copy_start, static_cast<std::size_t>(_emb_pte_portable__squeeze_copy_end - _emb_pte_portable__squeeze_copy_start),
    },
    { "stack", "portable__stack",
      _emb_pte_portable__stack_start, static_cast<std::size_t>(_emb_pte_portable__stack_end - _emb_pte_portable__stack_start),
    },
    { "sub", "portable__sub",
      _emb_pte_portable__sub_start, static_cast<std::size_t>(_emb_pte_portable__sub_end - _emb_pte_portable__sub_start),
    },
    { "sum", "portable__sum",
      _emb_pte_portable__sum_start, static_cast<std::size_t>(_emb_pte_portable__sum_end - _emb_pte_portable__sum_start),
    },
    { "t_copy", "portable__t_copy",
      _emb_pte_portable__t_copy_start, static_cast<std::size_t>(_emb_pte_portable__t_copy_end - _emb_pte_portable__t_copy_start),
    },
    { "tan", "portable__tan",
      _emb_pte_portable__tan_start, static_cast<std::size_t>(_emb_pte_portable__tan_end - _emb_pte_portable__tan_start),
    },
    { "tanh", "portable__tanh",
      _emb_pte_portable__tanh_start, static_cast<std::size_t>(_emb_pte_portable__tanh_end - _emb_pte_portable__tanh_start),
    },
    { "to_copy", "portable__to_copy",
      _emb_pte_portable__to_copy_start, static_cast<std::size_t>(_emb_pte_portable__to_copy_end - _emb_pte_portable__to_copy_start),
    },
    { "topk", "portable__topk",
      _emb_pte_portable__topk_start, static_cast<std::size_t>(_emb_pte_portable__topk_end - _emb_pte_portable__topk_start),
    },
    { "transpose_copy", "portable__transpose_copy",
      _emb_pte_portable__transpose_copy_start, static_cast<std::size_t>(_emb_pte_portable__transpose_copy_end - _emb_pte_portable__transpose_copy_start),
    },
    { "tril", "portable__tril",
      _emb_pte_portable__tril_start, static_cast<std::size_t>(_emb_pte_portable__tril_end - _emb_pte_portable__tril_start),
    },
    { "trunc", "portable__trunc",
      _emb_pte_portable__trunc_start, static_cast<std::size_t>(_emb_pte_portable__trunc_end - _emb_pte_portable__trunc_start),
    },
    { "unbind_copy", "portable__unbind_copy",
      _emb_pte_portable__unbind_copy_start, static_cast<std::size_t>(_emb_pte_portable__unbind_copy_end - _emb_pte_portable__unbind_copy_start),
    },
    { "unfold_copy", "portable__unfold_copy",
      _emb_pte_portable__unfold_copy_start, static_cast<std::size_t>(_emb_pte_portable__unfold_copy_end - _emb_pte_portable__unfold_copy_start),
    },
    { "unsqueeze_copy", "portable__unsqueeze_copy",
      _emb_pte_portable__unsqueeze_copy_start, static_cast<std::size_t>(_emb_pte_portable__unsqueeze_copy_end - _emb_pte_portable__unsqueeze_copy_start),
    },
    { "upsample_bilinear2d", "portable__upsample_bilinear2d",
      _emb_pte_portable__upsample_bilinear2d_start, static_cast<std::size_t>(_emb_pte_portable__upsample_bilinear2d_end - _emb_pte_portable__upsample_bilinear2d_start),
    },
    { "upsample_nearest2d", "portable__upsample_nearest2d",
      _emb_pte_portable__upsample_nearest2d_start, static_cast<std::size_t>(_emb_pte_portable__upsample_nearest2d_end - _emb_pte_portable__upsample_nearest2d_start),
    },
    { "var", "portable__var",
      _emb_pte_portable__var_start, static_cast<std::size_t>(_emb_pte_portable__var_end - _emb_pte_portable__var_start),
    },
    { "var_mean", "portable__var_mean",
      _emb_pte_portable__var_mean_start, static_cast<std::size_t>(_emb_pte_portable__var_mean_end - _emb_pte_portable__var_mean_start),
    },
    { "view_copy", "portable__view_copy",
      _emb_pte_portable__view_copy_start, static_cast<std::size_t>(_emb_pte_portable__view_copy_end - _emb_pte_portable__view_copy_start),
    },
    { "where", "portable__where",
      _emb_pte_portable__where_start, static_cast<std::size_t>(_emb_pte_portable__where_end - _emb_pte_portable__where_start),
    },
    { "dequantize_per_tensor", "cortex_m__dequantize_per_tensor",
      _emb_pte_cortex_m__dequantize_per_tensor_start, static_cast<std::size_t>(_emb_pte_cortex_m__dequantize_per_tensor_end - _emb_pte_cortex_m__dequantize_per_tensor_start),
    },
    { "maximum", "cortex_m__maximum",
      _emb_pte_cortex_m__maximum_start, static_cast<std::size_t>(_emb_pte_cortex_m__maximum_end - _emb_pte_cortex_m__maximum_start),
    },
    { "minimum", "cortex_m__minimum",
      _emb_pte_cortex_m__minimum_start, static_cast<std::size_t>(_emb_pte_cortex_m__minimum_end - _emb_pte_cortex_m__minimum_start),
    },
    { "pad", "cortex_m__pad",
      _emb_pte_cortex_m__pad_start, static_cast<std::size_t>(_emb_pte_cortex_m__pad_end - _emb_pte_cortex_m__pad_start),
    },
    { "quantize_per_tensor", "cortex_m__quantize_per_tensor",
      _emb_pte_cortex_m__quantize_per_tensor_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantize_per_tensor_end - _emb_pte_cortex_m__quantize_per_tensor_start),
    },
    { "quantized_add", "cortex_m__quantized_add",
      _emb_pte_cortex_m__quantized_add_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_add_end - _emb_pte_cortex_m__quantized_add_start),
    },
    { "quantized_avg_pool2d", "cortex_m__quantized_avg_pool2d",
      _emb_pte_cortex_m__quantized_avg_pool2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_avg_pool2d_end - _emb_pte_cortex_m__quantized_avg_pool2d_start),
    },
    { "quantized_batch_matmul", "cortex_m__quantized_batch_matmul",
      _emb_pte_cortex_m__quantized_batch_matmul_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_batch_matmul_end - _emb_pte_cortex_m__quantized_batch_matmul_start),
    },
    { "quantized_conv2d", "cortex_m__quantized_conv2d",
      _emb_pte_cortex_m__quantized_conv2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_conv2d_end - _emb_pte_cortex_m__quantized_conv2d_start),
    },
    { "quantized_depthwise_conv2d", "cortex_m__quantized_depthwise_conv2d",
      _emb_pte_cortex_m__quantized_depthwise_conv2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_depthwise_conv2d_end - _emb_pte_cortex_m__quantized_depthwise_conv2d_start),
    },
    { "quantized_linear", "cortex_m__quantized_linear",
      _emb_pte_cortex_m__quantized_linear_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_linear_end - _emb_pte_cortex_m__quantized_linear_start),
    },
    { "quantized_max_pool2d", "cortex_m__quantized_max_pool2d",
      _emb_pte_cortex_m__quantized_max_pool2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_max_pool2d_end - _emb_pte_cortex_m__quantized_max_pool2d_start),
    },
    { "quantized_mul", "cortex_m__quantized_mul",
      _emb_pte_cortex_m__quantized_mul_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_mul_end - _emb_pte_cortex_m__quantized_mul_start),
    },
    { "quantized_transpose_conv2d", "cortex_m__quantized_transpose_conv2d",
      _emb_pte_cortex_m__quantized_transpose_conv2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_transpose_conv2d_end - _emb_pte_cortex_m__quantized_transpose_conv2d_start),
    },
    { "softmax", "cortex_m__softmax",
      _emb_pte_cortex_m__softmax_start, static_cast<std::size_t>(_emb_pte_cortex_m__softmax_end - _emb_pte_cortex_m__softmax_start),
    },
    { "transpose", "cortex_m__transpose",
      _emb_pte_cortex_m__transpose_start, static_cast<std::size_t>(_emb_pte_cortex_m__transpose_end - _emb_pte_cortex_m__transpose_start),
    },
};

const std::size_t g_embedded_models_count = sizeof(g_embedded_models) / sizeof(g_embedded_models[0]);
