// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
#include "embedded_models.h"

extern "C" {
extern const unsigned char _emb_pte_portable__abs_start[];
extern const unsigned char _emb_pte_portable__abs_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__add_start[];
extern const unsigned char _emb_pte_portable__add_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__bitwise_and_start[];
extern const unsigned char _emb_pte_portable__bitwise_and_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__eq_start[];
extern const unsigned char _emb_pte_portable__eq_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__logical_and_start[];
extern const unsigned char _emb_pte_portable__logical_and_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_portable__logical_not_start[];
extern const unsigned char _emb_pte_portable__logical_not_end[];
}  // extern "C"

extern "C" {
extern const unsigned char _emb_pte_cortex_m__quantized_add_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_add_end[];
}  // extern "C"


const EmbeddedModel g_embedded_models[] = {
    { "abs", "portable__abs",
      _emb_pte_portable__abs_start, static_cast<std::size_t>(_emb_pte_portable__abs_end - _emb_pte_portable__abs_start),
    },
    { "add", "portable__add",
      _emb_pte_portable__add_start, static_cast<std::size_t>(_emb_pte_portable__add_end - _emb_pte_portable__add_start),
    },
    { "bitwise_and", "portable__bitwise_and",
      _emb_pte_portable__bitwise_and_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_and_end - _emb_pte_portable__bitwise_and_start),
    },
    { "eq", "portable__eq",
      _emb_pte_portable__eq_start, static_cast<std::size_t>(_emb_pte_portable__eq_end - _emb_pte_portable__eq_start),
    },
    { "logical_and", "portable__logical_and",
      _emb_pte_portable__logical_and_start, static_cast<std::size_t>(_emb_pte_portable__logical_and_end - _emb_pte_portable__logical_and_start),
    },
    { "logical_not", "portable__logical_not",
      _emb_pte_portable__logical_not_start, static_cast<std::size_t>(_emb_pte_portable__logical_not_end - _emb_pte_portable__logical_not_start),
    },
    { "quantized_add", "cortex_m__quantized_add",
      _emb_pte_cortex_m__quantized_add_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_add_end - _emb_pte_cortex_m__quantized_add_start),
    },
};

const std::size_t g_embedded_models_count = sizeof(g_embedded_models) / sizeof(g_embedded_models[0]);
