// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
#include "embedded_models.h"

extern "C" {
extern const unsigned char _emb_pte_portable__adaptive_avg_pool2d_start[];
extern const unsigned char _emb_pte_portable__adaptive_avg_pool2d_end[];
extern const unsigned char _emb_pte_portable__conj_physical_start[];
extern const unsigned char _emb_pte_portable__conj_physical_end[];
extern const unsigned char _emb_pte_portable__abs_start[];
extern const unsigned char _emb_pte_portable__abs_end[];
extern const unsigned char _emb_pte_portable__acos_start[];
extern const unsigned char _emb_pte_portable__acos_end[];
extern const unsigned char _emb_pte_portable__acosh_start[];
extern const unsigned char _emb_pte_portable__acosh_end[];
extern const unsigned char _emb_pte_portable__add_start[];
extern const unsigned char _emb_pte_portable__add_end[];
extern const unsigned char _emb_pte_portable__addmm_start[];
extern const unsigned char _emb_pte_portable__addmm_end[];
extern const unsigned char _emb_pte_portable__alias_copy_start[];
extern const unsigned char _emb_pte_portable__alias_copy_end[];
extern const unsigned char _emb_pte_portable__amax_start[];
extern const unsigned char _emb_pte_portable__amax_end[];
extern const unsigned char _emb_pte_portable__amin_start[];
extern const unsigned char _emb_pte_portable__amin_end[];
extern const unsigned char _emb_pte_portable__any_start[];
extern const unsigned char _emb_pte_portable__any_end[];
extern const unsigned char _emb_pte_portable__argmax_start[];
extern const unsigned char _emb_pte_portable__argmax_end[];
extern const unsigned char _emb_pte_portable__argmin_start[];
extern const unsigned char _emb_pte_portable__argmin_end[];
extern const unsigned char _emb_pte_portable__as_strided_copy_start[];
extern const unsigned char _emb_pte_portable__as_strided_copy_end[];
extern const unsigned char _emb_pte_portable__asin_start[];
extern const unsigned char _emb_pte_portable__asin_end[];
extern const unsigned char _emb_pte_portable__asinh_start[];
extern const unsigned char _emb_pte_portable__asinh_end[];
extern const unsigned char _emb_pte_portable__atan_start[];
extern const unsigned char _emb_pte_portable__atan_end[];
extern const unsigned char _emb_pte_portable__atan2_start[];
extern const unsigned char _emb_pte_portable__atan2_end[];
extern const unsigned char _emb_pte_portable__atanh_start[];
extern const unsigned char _emb_pte_portable__atanh_end[];
extern const unsigned char _emb_pte_portable__avg_pool2d_start[];
extern const unsigned char _emb_pte_portable__avg_pool2d_end[];
extern const unsigned char _emb_pte_portable__bitwise_and_start[];
extern const unsigned char _emb_pte_portable__bitwise_and_end[];
extern const unsigned char _emb_pte_portable__bitwise_left_shift_start[];
extern const unsigned char _emb_pte_portable__bitwise_left_shift_end[];
extern const unsigned char _emb_pte_portable__bitwise_not_start[];
extern const unsigned char _emb_pte_portable__bitwise_not_end[];
extern const unsigned char _emb_pte_portable__bitwise_or_start[];
extern const unsigned char _emb_pte_portable__bitwise_or_end[];
extern const unsigned char _emb_pte_portable__bitwise_right_shift_start[];
extern const unsigned char _emb_pte_portable__bitwise_right_shift_end[];
extern const unsigned char _emb_pte_portable__bitwise_xor_start[];
extern const unsigned char _emb_pte_portable__bitwise_xor_end[];
extern const unsigned char _emb_pte_portable__bmm_start[];
extern const unsigned char _emb_pte_portable__bmm_end[];
extern const unsigned char _emb_pte_portable__cat_start[];
extern const unsigned char _emb_pte_portable__cat_end[];
extern const unsigned char _emb_pte_portable__ceil_start[];
extern const unsigned char _emb_pte_portable__ceil_end[];
extern const unsigned char _emb_pte_portable__clamp_start[];
extern const unsigned char _emb_pte_portable__clamp_end[];
extern const unsigned char _emb_pte_portable__clone_start[];
extern const unsigned char _emb_pte_portable__clone_end[];
extern const unsigned char _emb_pte_portable__constant_pad_nd_start[];
extern const unsigned char _emb_pte_portable__constant_pad_nd_end[];
extern const unsigned char _emb_pte_portable__convolution_start[];
extern const unsigned char _emb_pte_portable__convolution_end[];
extern const unsigned char _emb_pte_portable__copy_start[];
extern const unsigned char _emb_pte_portable__copy_end[];
extern const unsigned char _emb_pte_portable__cos_start[];
extern const unsigned char _emb_pte_portable__cos_end[];
extern const unsigned char _emb_pte_portable__cosh_start[];
extern const unsigned char _emb_pte_portable__cosh_end[];
extern const unsigned char _emb_pte_portable__cumsum_start[];
extern const unsigned char _emb_pte_portable__cumsum_end[];
extern const unsigned char _emb_pte_portable__detach_copy_start[];
extern const unsigned char _emb_pte_portable__detach_copy_end[];
extern const unsigned char _emb_pte_portable__diagonal_copy_start[];
extern const unsigned char _emb_pte_portable__diagonal_copy_end[];
extern const unsigned char _emb_pte_portable__div_start[];
extern const unsigned char _emb_pte_portable__div_end[];
extern const unsigned char _emb_pte_portable__elu_start[];
extern const unsigned char _emb_pte_portable__elu_end[];
extern const unsigned char _emb_pte_portable__embedding_start[];
extern const unsigned char _emb_pte_portable__embedding_end[];
extern const unsigned char _emb_pte_portable__eq_start[];
extern const unsigned char _emb_pte_portable__eq_end[];
extern const unsigned char _emb_pte_portable__erf_start[];
extern const unsigned char _emb_pte_portable__erf_end[];
extern const unsigned char _emb_pte_portable__exp_start[];
extern const unsigned char _emb_pte_portable__exp_end[];
extern const unsigned char _emb_pte_portable__expand_copy_start[];
extern const unsigned char _emb_pte_portable__expand_copy_end[];
extern const unsigned char _emb_pte_portable__expm1_start[];
extern const unsigned char _emb_pte_portable__expm1_end[];
extern const unsigned char _emb_pte_portable__fill_start[];
extern const unsigned char _emb_pte_portable__fill_end[];
extern const unsigned char _emb_pte_portable__flip_start[];
extern const unsigned char _emb_pte_portable__flip_end[];
extern const unsigned char _emb_pte_portable__floor_start[];
extern const unsigned char _emb_pte_portable__floor_end[];
extern const unsigned char _emb_pte_portable__floor_divide_start[];
extern const unsigned char _emb_pte_portable__floor_divide_end[];
extern const unsigned char _emb_pte_portable__fmod_start[];
extern const unsigned char _emb_pte_portable__fmod_end[];
extern const unsigned char _emb_pte_portable__full_like_start[];
extern const unsigned char _emb_pte_portable__full_like_end[];
extern const unsigned char _emb_pte_portable__gather_start[];
extern const unsigned char _emb_pte_portable__gather_end[];
extern const unsigned char _emb_pte_portable__ge_start[];
extern const unsigned char _emb_pte_portable__ge_end[];
extern const unsigned char _emb_pte_portable__gelu_start[];
extern const unsigned char _emb_pte_portable__gelu_end[];
extern const unsigned char _emb_pte_portable__glu_start[];
extern const unsigned char _emb_pte_portable__glu_end[];
extern const unsigned char _emb_pte_portable__gt_start[];
extern const unsigned char _emb_pte_portable__gt_end[];
extern const unsigned char _emb_pte_portable__hardtanh_start[];
extern const unsigned char _emb_pte_portable__hardtanh_end[];
extern const unsigned char _emb_pte_portable__index_start[];
extern const unsigned char _emb_pte_portable__index_end[];
extern const unsigned char _emb_pte_portable__index_put_start[];
extern const unsigned char _emb_pte_portable__index_put_end[];
extern const unsigned char _emb_pte_portable__index_select_start[];
extern const unsigned char _emb_pte_portable__index_select_end[];
extern const unsigned char _emb_pte_portable__isinf_start[];
extern const unsigned char _emb_pte_portable__isinf_end[];
extern const unsigned char _emb_pte_portable__isnan_start[];
extern const unsigned char _emb_pte_portable__isnan_end[];
extern const unsigned char _emb_pte_portable__le_start[];
extern const unsigned char _emb_pte_portable__le_end[];
extern const unsigned char _emb_pte_portable__leaky_relu_start[];
extern const unsigned char _emb_pte_portable__leaky_relu_end[];
extern const unsigned char _emb_pte_portable__lift_fresh_copy_start[];
extern const unsigned char _emb_pte_portable__lift_fresh_copy_end[];
extern const unsigned char _emb_pte_portable__log_start[];
extern const unsigned char _emb_pte_portable__log_end[];
extern const unsigned char _emb_pte_portable__log10_start[];
extern const unsigned char _emb_pte_portable__log10_end[];
extern const unsigned char _emb_pte_portable__log1p_start[];
extern const unsigned char _emb_pte_portable__log1p_end[];
extern const unsigned char _emb_pte_portable__log2_start[];
extern const unsigned char _emb_pte_portable__log2_end[];
extern const unsigned char _emb_pte_portable__log_softmax_start[];
extern const unsigned char _emb_pte_portable__log_softmax_end[];
extern const unsigned char _emb_pte_portable__logical_and_start[];
extern const unsigned char _emb_pte_portable__logical_and_end[];
extern const unsigned char _emb_pte_portable__logical_not_start[];
extern const unsigned char _emb_pte_portable__logical_not_end[];
extern const unsigned char _emb_pte_portable__logical_or_start[];
extern const unsigned char _emb_pte_portable__logical_or_end[];
extern const unsigned char _emb_pte_portable__logical_xor_start[];
extern const unsigned char _emb_pte_portable__logical_xor_end[];
extern const unsigned char _emb_pte_portable__logit_start[];
extern const unsigned char _emb_pte_portable__logit_end[];
extern const unsigned char _emb_pte_portable__lt_start[];
extern const unsigned char _emb_pte_portable__lt_end[];
extern const unsigned char _emb_pte_portable__masked_fill_start[];
extern const unsigned char _emb_pte_portable__masked_fill_end[];
extern const unsigned char _emb_pte_portable__masked_scatter_start[];
extern const unsigned char _emb_pte_portable__masked_scatter_end[];
extern const unsigned char _emb_pte_portable__max_start[];
extern const unsigned char _emb_pte_portable__max_end[];
extern const unsigned char _emb_pte_portable__max_pool2d_with_indices_start[];
extern const unsigned char _emb_pte_portable__max_pool2d_with_indices_end[];
extern const unsigned char _emb_pte_portable__maximum_start[];
extern const unsigned char _emb_pte_portable__maximum_end[];
extern const unsigned char _emb_pte_portable__mean_start[];
extern const unsigned char _emb_pte_portable__mean_end[];
extern const unsigned char _emb_pte_portable__min_start[];
extern const unsigned char _emb_pte_portable__min_end[];
extern const unsigned char _emb_pte_portable__minimum_start[];
extern const unsigned char _emb_pte_portable__minimum_end[];
extern const unsigned char _emb_pte_portable__mm_start[];
extern const unsigned char _emb_pte_portable__mm_end[];
extern const unsigned char _emb_pte_portable__mul_start[];
extern const unsigned char _emb_pte_portable__mul_end[];
extern const unsigned char _emb_pte_portable__narrow_copy_start[];
extern const unsigned char _emb_pte_portable__narrow_copy_end[];
extern const unsigned char _emb_pte_portable__native_batch_norm_start[];
extern const unsigned char _emb_pte_portable__native_batch_norm_end[];
extern const unsigned char _emb_pte_portable__native_group_norm_start[];
extern const unsigned char _emb_pte_portable__native_group_norm_end[];
extern const unsigned char _emb_pte_portable__native_layer_norm_start[];
extern const unsigned char _emb_pte_portable__native_layer_norm_end[];
extern const unsigned char _emb_pte_portable__ne_start[];
extern const unsigned char _emb_pte_portable__ne_end[];
extern const unsigned char _emb_pte_portable__neg_start[];
extern const unsigned char _emb_pte_portable__neg_end[];
extern const unsigned char _emb_pte_portable__permute_copy_start[];
extern const unsigned char _emb_pte_portable__permute_copy_end[];
extern const unsigned char _emb_pte_portable__pixel_shuffle_start[];
extern const unsigned char _emb_pte_portable__pixel_shuffle_end[];
extern const unsigned char _emb_pte_portable__pixel_unshuffle_start[];
extern const unsigned char _emb_pte_portable__pixel_unshuffle_end[];
extern const unsigned char _emb_pte_portable__pow_start[];
extern const unsigned char _emb_pte_portable__pow_end[];
extern const unsigned char _emb_pte_portable__prod_start[];
extern const unsigned char _emb_pte_portable__prod_end[];
extern const unsigned char _emb_pte_portable__reciprocal_start[];
extern const unsigned char _emb_pte_portable__reciprocal_end[];
extern const unsigned char _emb_pte_portable__reflection_pad1d_start[];
extern const unsigned char _emb_pte_portable__reflection_pad1d_end[];
extern const unsigned char _emb_pte_portable__reflection_pad2d_start[];
extern const unsigned char _emb_pte_portable__reflection_pad2d_end[];
extern const unsigned char _emb_pte_portable__reflection_pad3d_start[];
extern const unsigned char _emb_pte_portable__reflection_pad3d_end[];
extern const unsigned char _emb_pte_portable__relu_start[];
extern const unsigned char _emb_pte_portable__relu_end[];
extern const unsigned char _emb_pte_portable__remainder_start[];
extern const unsigned char _emb_pte_portable__remainder_end[];
extern const unsigned char _emb_pte_portable__repeat_start[];
extern const unsigned char _emb_pte_portable__repeat_end[];
extern const unsigned char _emb_pte_portable__repeat_interleave_start[];
extern const unsigned char _emb_pte_portable__repeat_interleave_end[];
extern const unsigned char _emb_pte_portable__replication_pad1d_start[];
extern const unsigned char _emb_pte_portable__replication_pad1d_end[];
extern const unsigned char _emb_pte_portable__replication_pad2d_start[];
extern const unsigned char _emb_pte_portable__replication_pad2d_end[];
extern const unsigned char _emb_pte_portable__replication_pad3d_start[];
extern const unsigned char _emb_pte_portable__replication_pad3d_end[];
extern const unsigned char _emb_pte_portable__roll_start[];
extern const unsigned char _emb_pte_portable__roll_end[];
extern const unsigned char _emb_pte_portable__round_start[];
extern const unsigned char _emb_pte_portable__round_end[];
extern const unsigned char _emb_pte_portable__rsqrt_start[];
extern const unsigned char _emb_pte_portable__rsqrt_end[];
extern const unsigned char _emb_pte_portable__rsub_start[];
extern const unsigned char _emb_pte_portable__rsub_end[];
extern const unsigned char _emb_pte_portable__scatter_start[];
extern const unsigned char _emb_pte_portable__scatter_end[];
extern const unsigned char _emb_pte_portable__scatter_add_start[];
extern const unsigned char _emb_pte_portable__scatter_add_end[];
extern const unsigned char _emb_pte_portable__select_copy_start[];
extern const unsigned char _emb_pte_portable__select_copy_end[];
extern const unsigned char _emb_pte_portable__select_scatter_start[];
extern const unsigned char _emb_pte_portable__select_scatter_end[];
extern const unsigned char _emb_pte_portable__sigmoid_start[];
extern const unsigned char _emb_pte_portable__sigmoid_end[];
extern const unsigned char _emb_pte_portable__sign_start[];
extern const unsigned char _emb_pte_portable__sign_end[];
extern const unsigned char _emb_pte_portable__sin_start[];
extern const unsigned char _emb_pte_portable__sin_end[];
extern const unsigned char _emb_pte_portable__sinh_start[];
extern const unsigned char _emb_pte_portable__sinh_end[];
extern const unsigned char _emb_pte_portable__slice_copy_start[];
extern const unsigned char _emb_pte_portable__slice_copy_end[];
extern const unsigned char _emb_pte_portable__slice_scatter_start[];
extern const unsigned char _emb_pte_portable__slice_scatter_end[];
extern const unsigned char _emb_pte_portable__softmax_start[];
extern const unsigned char _emb_pte_portable__softmax_end[];
extern const unsigned char _emb_pte_portable__split_copy_start[];
extern const unsigned char _emb_pte_portable__split_copy_end[];
extern const unsigned char _emb_pte_portable__split_with_sizes_copy_start[];
extern const unsigned char _emb_pte_portable__split_with_sizes_copy_end[];
extern const unsigned char _emb_pte_portable__sqrt_start[];
extern const unsigned char _emb_pte_portable__sqrt_end[];
extern const unsigned char _emb_pte_portable__squeeze_copy_start[];
extern const unsigned char _emb_pte_portable__squeeze_copy_end[];
extern const unsigned char _emb_pte_portable__stack_start[];
extern const unsigned char _emb_pte_portable__stack_end[];
extern const unsigned char _emb_pte_portable__sub_start[];
extern const unsigned char _emb_pte_portable__sub_end[];
extern const unsigned char _emb_pte_portable__sum_start[];
extern const unsigned char _emb_pte_portable__sum_end[];
extern const unsigned char _emb_pte_portable__t_copy_start[];
extern const unsigned char _emb_pte_portable__t_copy_end[];
extern const unsigned char _emb_pte_portable__tan_start[];
extern const unsigned char _emb_pte_portable__tan_end[];
extern const unsigned char _emb_pte_portable__tanh_start[];
extern const unsigned char _emb_pte_portable__tanh_end[];
extern const unsigned char _emb_pte_portable__to_copy_start[];
extern const unsigned char _emb_pte_portable__to_copy_end[];
extern const unsigned char _emb_pte_portable__topk_start[];
extern const unsigned char _emb_pte_portable__topk_end[];
extern const unsigned char _emb_pte_portable__transpose_copy_start[];
extern const unsigned char _emb_pte_portable__transpose_copy_end[];
extern const unsigned char _emb_pte_portable__tril_start[];
extern const unsigned char _emb_pte_portable__tril_end[];
extern const unsigned char _emb_pte_portable__trunc_start[];
extern const unsigned char _emb_pte_portable__trunc_end[];
extern const unsigned char _emb_pte_portable__unbind_copy_start[];
extern const unsigned char _emb_pte_portable__unbind_copy_end[];
extern const unsigned char _emb_pte_portable__unfold_copy_start[];
extern const unsigned char _emb_pte_portable__unfold_copy_end[];
extern const unsigned char _emb_pte_portable__unsqueeze_copy_start[];
extern const unsigned char _emb_pte_portable__unsqueeze_copy_end[];
extern const unsigned char _emb_pte_portable__upsample_bilinear2d_start[];
extern const unsigned char _emb_pte_portable__upsample_bilinear2d_end[];
extern const unsigned char _emb_pte_portable__upsample_nearest2d_start[];
extern const unsigned char _emb_pte_portable__upsample_nearest2d_end[];
extern const unsigned char _emb_pte_portable__var_start[];
extern const unsigned char _emb_pte_portable__var_end[];
extern const unsigned char _emb_pte_portable__var_mean_start[];
extern const unsigned char _emb_pte_portable__var_mean_end[];
extern const unsigned char _emb_pte_portable__view_copy_start[];
extern const unsigned char _emb_pte_portable__view_copy_end[];
extern const unsigned char _emb_pte_portable__where_start[];
extern const unsigned char _emb_pte_portable__where_end[];
extern const unsigned char _emb_pte_cortex_m__dequantize_per_tensor_start[];
extern const unsigned char _emb_pte_cortex_m__dequantize_per_tensor_end[];
extern const unsigned char _emb_pte_cortex_m__maximum_start[];
extern const unsigned char _emb_pte_cortex_m__maximum_end[];
extern const unsigned char _emb_pte_cortex_m__minimum_start[];
extern const unsigned char _emb_pte_cortex_m__minimum_end[];
extern const unsigned char _emb_pte_cortex_m__pad_start[];
extern const unsigned char _emb_pte_cortex_m__pad_end[];
extern const unsigned char _emb_pte_cortex_m__quantize_per_tensor_start[];
extern const unsigned char _emb_pte_cortex_m__quantize_per_tensor_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_add_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_add_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_avg_pool2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_avg_pool2d_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_batch_matmul_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_batch_matmul_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_conv2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_conv2d_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_depthwise_conv2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_depthwise_conv2d_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_linear_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_linear_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_max_pool2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_max_pool2d_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_mul_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_mul_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_transpose_conv2d_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_transpose_conv2d_end[];
extern const unsigned char _emb_pte_cortex_m__softmax_start[];
extern const unsigned char _emb_pte_cortex_m__softmax_end[];
extern const unsigned char _emb_pte_cortex_m__transpose_start[];
extern const unsigned char _emb_pte_cortex_m__transpose_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_depthwise_conv2d_deep_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_depthwise_conv2d_deep_end[];
extern const unsigned char _emb_pte_cortex_m__quantized_conv2d_1xn_pad_start[];
extern const unsigned char _emb_pte_cortex_m__quantized_conv2d_1xn_pad_end[];
}  // extern "C"

const EmbeddedModel g_embedded_models[] = {
    { "adaptive_avg_pool2d", "Portable",
      _emb_pte_portable__adaptive_avg_pool2d_start, static_cast<std::size_t>(_emb_pte_portable__adaptive_avg_pool2d_end - _emb_pte_portable__adaptive_avg_pool2d_start) },
    { "conj_physical", "Portable",
      _emb_pte_portable__conj_physical_start, static_cast<std::size_t>(_emb_pte_portable__conj_physical_end - _emb_pte_portable__conj_physical_start) },
    { "abs", "Portable",
      _emb_pte_portable__abs_start, static_cast<std::size_t>(_emb_pte_portable__abs_end - _emb_pte_portable__abs_start) },
    { "acos", "Portable",
      _emb_pte_portable__acos_start, static_cast<std::size_t>(_emb_pte_portable__acos_end - _emb_pte_portable__acos_start) },
    { "acosh", "Portable",
      _emb_pte_portable__acosh_start, static_cast<std::size_t>(_emb_pte_portable__acosh_end - _emb_pte_portable__acosh_start) },
    { "add", "Portable",
      _emb_pte_portable__add_start, static_cast<std::size_t>(_emb_pte_portable__add_end - _emb_pte_portable__add_start) },
    { "addmm", "Portable",
      _emb_pte_portable__addmm_start, static_cast<std::size_t>(_emb_pte_portable__addmm_end - _emb_pte_portable__addmm_start) },
    { "alias_copy", "Portable",
      _emb_pte_portable__alias_copy_start, static_cast<std::size_t>(_emb_pte_portable__alias_copy_end - _emb_pte_portable__alias_copy_start) },
    { "amax", "Portable",
      _emb_pte_portable__amax_start, static_cast<std::size_t>(_emb_pte_portable__amax_end - _emb_pte_portable__amax_start) },
    { "amin", "Portable",
      _emb_pte_portable__amin_start, static_cast<std::size_t>(_emb_pte_portable__amin_end - _emb_pte_portable__amin_start) },
    { "any", "Portable",
      _emb_pte_portable__any_start, static_cast<std::size_t>(_emb_pte_portable__any_end - _emb_pte_portable__any_start) },
    { "argmax", "Portable",
      _emb_pte_portable__argmax_start, static_cast<std::size_t>(_emb_pte_portable__argmax_end - _emb_pte_portable__argmax_start) },
    { "argmin", "Portable",
      _emb_pte_portable__argmin_start, static_cast<std::size_t>(_emb_pte_portable__argmin_end - _emb_pte_portable__argmin_start) },
    { "as_strided_copy", "Portable",
      _emb_pte_portable__as_strided_copy_start, static_cast<std::size_t>(_emb_pte_portable__as_strided_copy_end - _emb_pte_portable__as_strided_copy_start) },
    { "asin", "Portable",
      _emb_pte_portable__asin_start, static_cast<std::size_t>(_emb_pte_portable__asin_end - _emb_pte_portable__asin_start) },
    { "asinh", "Portable",
      _emb_pte_portable__asinh_start, static_cast<std::size_t>(_emb_pte_portable__asinh_end - _emb_pte_portable__asinh_start) },
    { "atan", "Portable",
      _emb_pte_portable__atan_start, static_cast<std::size_t>(_emb_pte_portable__atan_end - _emb_pte_portable__atan_start) },
    { "atan2", "Portable",
      _emb_pte_portable__atan2_start, static_cast<std::size_t>(_emb_pte_portable__atan2_end - _emb_pte_portable__atan2_start) },
    { "atanh", "Portable",
      _emb_pte_portable__atanh_start, static_cast<std::size_t>(_emb_pte_portable__atanh_end - _emb_pte_portable__atanh_start) },
    { "avg_pool2d", "Portable",
      _emb_pte_portable__avg_pool2d_start, static_cast<std::size_t>(_emb_pte_portable__avg_pool2d_end - _emb_pte_portable__avg_pool2d_start) },
    { "bitwise_and", "Portable",
      _emb_pte_portable__bitwise_and_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_and_end - _emb_pte_portable__bitwise_and_start) },
    { "bitwise_left_shift", "Portable",
      _emb_pte_portable__bitwise_left_shift_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_left_shift_end - _emb_pte_portable__bitwise_left_shift_start) },
    { "bitwise_not", "Portable",
      _emb_pte_portable__bitwise_not_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_not_end - _emb_pte_portable__bitwise_not_start) },
    { "bitwise_or", "Portable",
      _emb_pte_portable__bitwise_or_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_or_end - _emb_pte_portable__bitwise_or_start) },
    { "bitwise_right_shift", "Portable",
      _emb_pte_portable__bitwise_right_shift_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_right_shift_end - _emb_pte_portable__bitwise_right_shift_start) },
    { "bitwise_xor", "Portable",
      _emb_pte_portable__bitwise_xor_start, static_cast<std::size_t>(_emb_pte_portable__bitwise_xor_end - _emb_pte_portable__bitwise_xor_start) },
    { "bmm", "Portable",
      _emb_pte_portable__bmm_start, static_cast<std::size_t>(_emb_pte_portable__bmm_end - _emb_pte_portable__bmm_start) },
    { "cat", "Portable",
      _emb_pte_portable__cat_start, static_cast<std::size_t>(_emb_pte_portable__cat_end - _emb_pte_portable__cat_start) },
    { "ceil", "Portable",
      _emb_pte_portable__ceil_start, static_cast<std::size_t>(_emb_pte_portable__ceil_end - _emb_pte_portable__ceil_start) },
    { "clamp", "Portable",
      _emb_pte_portable__clamp_start, static_cast<std::size_t>(_emb_pte_portable__clamp_end - _emb_pte_portable__clamp_start) },
    { "clone", "Portable",
      _emb_pte_portable__clone_start, static_cast<std::size_t>(_emb_pte_portable__clone_end - _emb_pte_portable__clone_start) },
    { "constant_pad_nd", "Portable",
      _emb_pte_portable__constant_pad_nd_start, static_cast<std::size_t>(_emb_pte_portable__constant_pad_nd_end - _emb_pte_portable__constant_pad_nd_start) },
    { "convolution", "Portable",
      _emb_pte_portable__convolution_start, static_cast<std::size_t>(_emb_pte_portable__convolution_end - _emb_pte_portable__convolution_start) },
    { "copy", "Portable",
      _emb_pte_portable__copy_start, static_cast<std::size_t>(_emb_pte_portable__copy_end - _emb_pte_portable__copy_start) },
    { "cos", "Portable",
      _emb_pte_portable__cos_start, static_cast<std::size_t>(_emb_pte_portable__cos_end - _emb_pte_portable__cos_start) },
    { "cosh", "Portable",
      _emb_pte_portable__cosh_start, static_cast<std::size_t>(_emb_pte_portable__cosh_end - _emb_pte_portable__cosh_start) },
    { "cumsum", "Portable",
      _emb_pte_portable__cumsum_start, static_cast<std::size_t>(_emb_pte_portable__cumsum_end - _emb_pte_portable__cumsum_start) },
    { "detach_copy", "Portable",
      _emb_pte_portable__detach_copy_start, static_cast<std::size_t>(_emb_pte_portable__detach_copy_end - _emb_pte_portable__detach_copy_start) },
    { "diagonal_copy", "Portable",
      _emb_pte_portable__diagonal_copy_start, static_cast<std::size_t>(_emb_pte_portable__diagonal_copy_end - _emb_pte_portable__diagonal_copy_start) },
    { "div", "Portable",
      _emb_pte_portable__div_start, static_cast<std::size_t>(_emb_pte_portable__div_end - _emb_pte_portable__div_start) },
    { "elu", "Portable",
      _emb_pte_portable__elu_start, static_cast<std::size_t>(_emb_pte_portable__elu_end - _emb_pte_portable__elu_start) },
    { "embedding", "Portable",
      _emb_pte_portable__embedding_start, static_cast<std::size_t>(_emb_pte_portable__embedding_end - _emb_pte_portable__embedding_start) },
    { "eq", "Portable",
      _emb_pte_portable__eq_start, static_cast<std::size_t>(_emb_pte_portable__eq_end - _emb_pte_portable__eq_start) },
    { "erf", "Portable",
      _emb_pte_portable__erf_start, static_cast<std::size_t>(_emb_pte_portable__erf_end - _emb_pte_portable__erf_start) },
    { "exp", "Portable",
      _emb_pte_portable__exp_start, static_cast<std::size_t>(_emb_pte_portable__exp_end - _emb_pte_portable__exp_start) },
    { "expand_copy", "Portable",
      _emb_pte_portable__expand_copy_start, static_cast<std::size_t>(_emb_pte_portable__expand_copy_end - _emb_pte_portable__expand_copy_start) },
    { "expm1", "Portable",
      _emb_pte_portable__expm1_start, static_cast<std::size_t>(_emb_pte_portable__expm1_end - _emb_pte_portable__expm1_start) },
    { "fill", "Portable",
      _emb_pte_portable__fill_start, static_cast<std::size_t>(_emb_pte_portable__fill_end - _emb_pte_portable__fill_start) },
    { "flip", "Portable",
      _emb_pte_portable__flip_start, static_cast<std::size_t>(_emb_pte_portable__flip_end - _emb_pte_portable__flip_start) },
    { "floor", "Portable",
      _emb_pte_portable__floor_start, static_cast<std::size_t>(_emb_pte_portable__floor_end - _emb_pte_portable__floor_start) },
    { "floor_divide", "Portable",
      _emb_pte_portable__floor_divide_start, static_cast<std::size_t>(_emb_pte_portable__floor_divide_end - _emb_pte_portable__floor_divide_start) },
    { "fmod", "Portable",
      _emb_pte_portable__fmod_start, static_cast<std::size_t>(_emb_pte_portable__fmod_end - _emb_pte_portable__fmod_start) },
    { "full_like", "Portable",
      _emb_pte_portable__full_like_start, static_cast<std::size_t>(_emb_pte_portable__full_like_end - _emb_pte_portable__full_like_start) },
    { "gather", "Portable",
      _emb_pte_portable__gather_start, static_cast<std::size_t>(_emb_pte_portable__gather_end - _emb_pte_portable__gather_start) },
    { "ge", "Portable",
      _emb_pte_portable__ge_start, static_cast<std::size_t>(_emb_pte_portable__ge_end - _emb_pte_portable__ge_start) },
    { "gelu", "Portable",
      _emb_pte_portable__gelu_start, static_cast<std::size_t>(_emb_pte_portable__gelu_end - _emb_pte_portable__gelu_start) },
    { "glu", "Portable",
      _emb_pte_portable__glu_start, static_cast<std::size_t>(_emb_pte_portable__glu_end - _emb_pte_portable__glu_start) },
    { "gt", "Portable",
      _emb_pte_portable__gt_start, static_cast<std::size_t>(_emb_pte_portable__gt_end - _emb_pte_portable__gt_start) },
    { "hardtanh", "Portable",
      _emb_pte_portable__hardtanh_start, static_cast<std::size_t>(_emb_pte_portable__hardtanh_end - _emb_pte_portable__hardtanh_start) },
    { "index", "Portable",
      _emb_pte_portable__index_start, static_cast<std::size_t>(_emb_pte_portable__index_end - _emb_pte_portable__index_start) },
    { "index_put", "Portable",
      _emb_pte_portable__index_put_start, static_cast<std::size_t>(_emb_pte_portable__index_put_end - _emb_pte_portable__index_put_start) },
    { "index_select", "Portable",
      _emb_pte_portable__index_select_start, static_cast<std::size_t>(_emb_pte_portable__index_select_end - _emb_pte_portable__index_select_start) },
    { "isinf", "Portable",
      _emb_pte_portable__isinf_start, static_cast<std::size_t>(_emb_pte_portable__isinf_end - _emb_pte_portable__isinf_start) },
    { "isnan", "Portable",
      _emb_pte_portable__isnan_start, static_cast<std::size_t>(_emb_pte_portable__isnan_end - _emb_pte_portable__isnan_start) },
    { "le", "Portable",
      _emb_pte_portable__le_start, static_cast<std::size_t>(_emb_pte_portable__le_end - _emb_pte_portable__le_start) },
    { "leaky_relu", "Portable",
      _emb_pte_portable__leaky_relu_start, static_cast<std::size_t>(_emb_pte_portable__leaky_relu_end - _emb_pte_portable__leaky_relu_start) },
    { "lift_fresh_copy", "Portable",
      _emb_pte_portable__lift_fresh_copy_start, static_cast<std::size_t>(_emb_pte_portable__lift_fresh_copy_end - _emb_pte_portable__lift_fresh_copy_start) },
    { "log", "Portable",
      _emb_pte_portable__log_start, static_cast<std::size_t>(_emb_pte_portable__log_end - _emb_pte_portable__log_start) },
    { "log10", "Portable",
      _emb_pte_portable__log10_start, static_cast<std::size_t>(_emb_pte_portable__log10_end - _emb_pte_portable__log10_start) },
    { "log1p", "Portable",
      _emb_pte_portable__log1p_start, static_cast<std::size_t>(_emb_pte_portable__log1p_end - _emb_pte_portable__log1p_start) },
    { "log2", "Portable",
      _emb_pte_portable__log2_start, static_cast<std::size_t>(_emb_pte_portable__log2_end - _emb_pte_portable__log2_start) },
    { "log_softmax", "Portable",
      _emb_pte_portable__log_softmax_start, static_cast<std::size_t>(_emb_pte_portable__log_softmax_end - _emb_pte_portable__log_softmax_start) },
    { "logical_and", "Portable",
      _emb_pte_portable__logical_and_start, static_cast<std::size_t>(_emb_pte_portable__logical_and_end - _emb_pte_portable__logical_and_start) },
    { "logical_not", "Portable",
      _emb_pte_portable__logical_not_start, static_cast<std::size_t>(_emb_pte_portable__logical_not_end - _emb_pte_portable__logical_not_start) },
    { "logical_or", "Portable",
      _emb_pte_portable__logical_or_start, static_cast<std::size_t>(_emb_pte_portable__logical_or_end - _emb_pte_portable__logical_or_start) },
    { "logical_xor", "Portable",
      _emb_pte_portable__logical_xor_start, static_cast<std::size_t>(_emb_pte_portable__logical_xor_end - _emb_pte_portable__logical_xor_start) },
    { "logit", "Portable",
      _emb_pte_portable__logit_start, static_cast<std::size_t>(_emb_pte_portable__logit_end - _emb_pte_portable__logit_start) },
    { "lt", "Portable",
      _emb_pte_portable__lt_start, static_cast<std::size_t>(_emb_pte_portable__lt_end - _emb_pte_portable__lt_start) },
    { "masked_fill", "Portable",
      _emb_pte_portable__masked_fill_start, static_cast<std::size_t>(_emb_pte_portable__masked_fill_end - _emb_pte_portable__masked_fill_start) },
    { "masked_scatter", "Portable",
      _emb_pte_portable__masked_scatter_start, static_cast<std::size_t>(_emb_pte_portable__masked_scatter_end - _emb_pte_portable__masked_scatter_start) },
    { "max", "Portable",
      _emb_pte_portable__max_start, static_cast<std::size_t>(_emb_pte_portable__max_end - _emb_pte_portable__max_start) },
    { "max_pool2d_with_indices", "Portable",
      _emb_pte_portable__max_pool2d_with_indices_start, static_cast<std::size_t>(_emb_pte_portable__max_pool2d_with_indices_end - _emb_pte_portable__max_pool2d_with_indices_start) },
    { "maximum", "Portable",
      _emb_pte_portable__maximum_start, static_cast<std::size_t>(_emb_pte_portable__maximum_end - _emb_pte_portable__maximum_start) },
    { "mean", "Portable",
      _emb_pte_portable__mean_start, static_cast<std::size_t>(_emb_pte_portable__mean_end - _emb_pte_portable__mean_start) },
    { "min", "Portable",
      _emb_pte_portable__min_start, static_cast<std::size_t>(_emb_pte_portable__min_end - _emb_pte_portable__min_start) },
    { "minimum", "Portable",
      _emb_pte_portable__minimum_start, static_cast<std::size_t>(_emb_pte_portable__minimum_end - _emb_pte_portable__minimum_start) },
    { "mm", "Portable",
      _emb_pte_portable__mm_start, static_cast<std::size_t>(_emb_pte_portable__mm_end - _emb_pte_portable__mm_start) },
    { "mul", "Portable",
      _emb_pte_portable__mul_start, static_cast<std::size_t>(_emb_pte_portable__mul_end - _emb_pte_portable__mul_start) },
    { "narrow_copy", "Portable",
      _emb_pte_portable__narrow_copy_start, static_cast<std::size_t>(_emb_pte_portable__narrow_copy_end - _emb_pte_portable__narrow_copy_start) },
    { "native_batch_norm", "Portable",
      _emb_pte_portable__native_batch_norm_start, static_cast<std::size_t>(_emb_pte_portable__native_batch_norm_end - _emb_pte_portable__native_batch_norm_start) },
    { "native_group_norm", "Portable",
      _emb_pte_portable__native_group_norm_start, static_cast<std::size_t>(_emb_pte_portable__native_group_norm_end - _emb_pte_portable__native_group_norm_start) },
    { "native_layer_norm", "Portable",
      _emb_pte_portable__native_layer_norm_start, static_cast<std::size_t>(_emb_pte_portable__native_layer_norm_end - _emb_pte_portable__native_layer_norm_start) },
    { "ne", "Portable",
      _emb_pte_portable__ne_start, static_cast<std::size_t>(_emb_pte_portable__ne_end - _emb_pte_portable__ne_start) },
    { "neg", "Portable",
      _emb_pte_portable__neg_start, static_cast<std::size_t>(_emb_pte_portable__neg_end - _emb_pte_portable__neg_start) },
    { "permute_copy", "Portable",
      _emb_pte_portable__permute_copy_start, static_cast<std::size_t>(_emb_pte_portable__permute_copy_end - _emb_pte_portable__permute_copy_start) },
    { "pixel_shuffle", "Portable",
      _emb_pte_portable__pixel_shuffle_start, static_cast<std::size_t>(_emb_pte_portable__pixel_shuffle_end - _emb_pte_portable__pixel_shuffle_start) },
    { "pixel_unshuffle", "Portable",
      _emb_pte_portable__pixel_unshuffle_start, static_cast<std::size_t>(_emb_pte_portable__pixel_unshuffle_end - _emb_pte_portable__pixel_unshuffle_start) },
    { "pow", "Portable",
      _emb_pte_portable__pow_start, static_cast<std::size_t>(_emb_pte_portable__pow_end - _emb_pte_portable__pow_start) },
    { "prod", "Portable",
      _emb_pte_portable__prod_start, static_cast<std::size_t>(_emb_pte_portable__prod_end - _emb_pte_portable__prod_start) },
    { "reciprocal", "Portable",
      _emb_pte_portable__reciprocal_start, static_cast<std::size_t>(_emb_pte_portable__reciprocal_end - _emb_pte_portable__reciprocal_start) },
    { "reflection_pad1d", "Portable",
      _emb_pte_portable__reflection_pad1d_start, static_cast<std::size_t>(_emb_pte_portable__reflection_pad1d_end - _emb_pte_portable__reflection_pad1d_start) },
    { "reflection_pad2d", "Portable",
      _emb_pte_portable__reflection_pad2d_start, static_cast<std::size_t>(_emb_pte_portable__reflection_pad2d_end - _emb_pte_portable__reflection_pad2d_start) },
    { "reflection_pad3d", "Portable",
      _emb_pte_portable__reflection_pad3d_start, static_cast<std::size_t>(_emb_pte_portable__reflection_pad3d_end - _emb_pte_portable__reflection_pad3d_start) },
    { "relu", "Portable",
      _emb_pte_portable__relu_start, static_cast<std::size_t>(_emb_pte_portable__relu_end - _emb_pte_portable__relu_start) },
    { "remainder", "Portable",
      _emb_pte_portable__remainder_start, static_cast<std::size_t>(_emb_pte_portable__remainder_end - _emb_pte_portable__remainder_start) },
    { "repeat", "Portable",
      _emb_pte_portable__repeat_start, static_cast<std::size_t>(_emb_pte_portable__repeat_end - _emb_pte_portable__repeat_start) },
    { "repeat_interleave", "Portable",
      _emb_pte_portable__repeat_interleave_start, static_cast<std::size_t>(_emb_pte_portable__repeat_interleave_end - _emb_pte_portable__repeat_interleave_start) },
    { "replication_pad1d", "Portable",
      _emb_pte_portable__replication_pad1d_start, static_cast<std::size_t>(_emb_pte_portable__replication_pad1d_end - _emb_pte_portable__replication_pad1d_start) },
    { "replication_pad2d", "Portable",
      _emb_pte_portable__replication_pad2d_start, static_cast<std::size_t>(_emb_pte_portable__replication_pad2d_end - _emb_pte_portable__replication_pad2d_start) },
    { "replication_pad3d", "Portable",
      _emb_pte_portable__replication_pad3d_start, static_cast<std::size_t>(_emb_pte_portable__replication_pad3d_end - _emb_pte_portable__replication_pad3d_start) },
    { "roll", "Portable",
      _emb_pte_portable__roll_start, static_cast<std::size_t>(_emb_pte_portable__roll_end - _emb_pte_portable__roll_start) },
    { "round", "Portable",
      _emb_pte_portable__round_start, static_cast<std::size_t>(_emb_pte_portable__round_end - _emb_pte_portable__round_start) },
    { "rsqrt", "Portable",
      _emb_pte_portable__rsqrt_start, static_cast<std::size_t>(_emb_pte_portable__rsqrt_end - _emb_pte_portable__rsqrt_start) },
    { "rsub", "Portable",
      _emb_pte_portable__rsub_start, static_cast<std::size_t>(_emb_pte_portable__rsub_end - _emb_pte_portable__rsub_start) },
    { "scatter", "Portable",
      _emb_pte_portable__scatter_start, static_cast<std::size_t>(_emb_pte_portable__scatter_end - _emb_pte_portable__scatter_start) },
    { "scatter_add", "Portable",
      _emb_pte_portable__scatter_add_start, static_cast<std::size_t>(_emb_pte_portable__scatter_add_end - _emb_pte_portable__scatter_add_start) },
    { "select_copy", "Portable",
      _emb_pte_portable__select_copy_start, static_cast<std::size_t>(_emb_pte_portable__select_copy_end - _emb_pte_portable__select_copy_start) },
    { "select_scatter", "Portable",
      _emb_pte_portable__select_scatter_start, static_cast<std::size_t>(_emb_pte_portable__select_scatter_end - _emb_pte_portable__select_scatter_start) },
    { "sigmoid", "Portable",
      _emb_pte_portable__sigmoid_start, static_cast<std::size_t>(_emb_pte_portable__sigmoid_end - _emb_pte_portable__sigmoid_start) },
    { "sign", "Portable",
      _emb_pte_portable__sign_start, static_cast<std::size_t>(_emb_pte_portable__sign_end - _emb_pte_portable__sign_start) },
    { "sin", "Portable",
      _emb_pte_portable__sin_start, static_cast<std::size_t>(_emb_pte_portable__sin_end - _emb_pte_portable__sin_start) },
    { "sinh", "Portable",
      _emb_pte_portable__sinh_start, static_cast<std::size_t>(_emb_pte_portable__sinh_end - _emb_pte_portable__sinh_start) },
    { "slice_copy", "Portable",
      _emb_pte_portable__slice_copy_start, static_cast<std::size_t>(_emb_pte_portable__slice_copy_end - _emb_pte_portable__slice_copy_start) },
    { "slice_scatter", "Portable",
      _emb_pte_portable__slice_scatter_start, static_cast<std::size_t>(_emb_pte_portable__slice_scatter_end - _emb_pte_portable__slice_scatter_start) },
    { "softmax", "Portable",
      _emb_pte_portable__softmax_start, static_cast<std::size_t>(_emb_pte_portable__softmax_end - _emb_pte_portable__softmax_start) },
    { "split_copy", "Portable",
      _emb_pte_portable__split_copy_start, static_cast<std::size_t>(_emb_pte_portable__split_copy_end - _emb_pte_portable__split_copy_start) },
    { "split_with_sizes_copy", "Portable",
      _emb_pte_portable__split_with_sizes_copy_start, static_cast<std::size_t>(_emb_pte_portable__split_with_sizes_copy_end - _emb_pte_portable__split_with_sizes_copy_start) },
    { "sqrt", "Portable",
      _emb_pte_portable__sqrt_start, static_cast<std::size_t>(_emb_pte_portable__sqrt_end - _emb_pte_portable__sqrt_start) },
    { "squeeze_copy", "Portable",
      _emb_pte_portable__squeeze_copy_start, static_cast<std::size_t>(_emb_pte_portable__squeeze_copy_end - _emb_pte_portable__squeeze_copy_start) },
    { "stack", "Portable",
      _emb_pte_portable__stack_start, static_cast<std::size_t>(_emb_pte_portable__stack_end - _emb_pte_portable__stack_start) },
    { "sub", "Portable",
      _emb_pte_portable__sub_start, static_cast<std::size_t>(_emb_pte_portable__sub_end - _emb_pte_portable__sub_start) },
    { "sum", "Portable",
      _emb_pte_portable__sum_start, static_cast<std::size_t>(_emb_pte_portable__sum_end - _emb_pte_portable__sum_start) },
    { "t_copy", "Portable",
      _emb_pte_portable__t_copy_start, static_cast<std::size_t>(_emb_pte_portable__t_copy_end - _emb_pte_portable__t_copy_start) },
    { "tan", "Portable",
      _emb_pte_portable__tan_start, static_cast<std::size_t>(_emb_pte_portable__tan_end - _emb_pte_portable__tan_start) },
    { "tanh", "Portable",
      _emb_pte_portable__tanh_start, static_cast<std::size_t>(_emb_pte_portable__tanh_end - _emb_pte_portable__tanh_start) },
    { "to_copy", "Portable",
      _emb_pte_portable__to_copy_start, static_cast<std::size_t>(_emb_pte_portable__to_copy_end - _emb_pte_portable__to_copy_start) },
    { "topk", "Portable",
      _emb_pte_portable__topk_start, static_cast<std::size_t>(_emb_pte_portable__topk_end - _emb_pte_portable__topk_start) },
    { "transpose_copy", "Portable",
      _emb_pte_portable__transpose_copy_start, static_cast<std::size_t>(_emb_pte_portable__transpose_copy_end - _emb_pte_portable__transpose_copy_start) },
    { "tril", "Portable",
      _emb_pte_portable__tril_start, static_cast<std::size_t>(_emb_pte_portable__tril_end - _emb_pte_portable__tril_start) },
    { "trunc", "Portable",
      _emb_pte_portable__trunc_start, static_cast<std::size_t>(_emb_pte_portable__trunc_end - _emb_pte_portable__trunc_start) },
    { "unbind_copy", "Portable",
      _emb_pte_portable__unbind_copy_start, static_cast<std::size_t>(_emb_pte_portable__unbind_copy_end - _emb_pte_portable__unbind_copy_start) },
    { "unfold_copy", "Portable",
      _emb_pte_portable__unfold_copy_start, static_cast<std::size_t>(_emb_pte_portable__unfold_copy_end - _emb_pte_portable__unfold_copy_start) },
    { "unsqueeze_copy", "Portable",
      _emb_pte_portable__unsqueeze_copy_start, static_cast<std::size_t>(_emb_pte_portable__unsqueeze_copy_end - _emb_pte_portable__unsqueeze_copy_start) },
    { "upsample_bilinear2d", "Portable",
      _emb_pte_portable__upsample_bilinear2d_start, static_cast<std::size_t>(_emb_pte_portable__upsample_bilinear2d_end - _emb_pte_portable__upsample_bilinear2d_start) },
    { "upsample_nearest2d", "Portable",
      _emb_pte_portable__upsample_nearest2d_start, static_cast<std::size_t>(_emb_pte_portable__upsample_nearest2d_end - _emb_pte_portable__upsample_nearest2d_start) },
    { "var", "Portable",
      _emb_pte_portable__var_start, static_cast<std::size_t>(_emb_pte_portable__var_end - _emb_pte_portable__var_start) },
    { "var_mean", "Portable",
      _emb_pte_portable__var_mean_start, static_cast<std::size_t>(_emb_pte_portable__var_mean_end - _emb_pte_portable__var_mean_start) },
    { "view_copy", "Portable",
      _emb_pte_portable__view_copy_start, static_cast<std::size_t>(_emb_pte_portable__view_copy_end - _emb_pte_portable__view_copy_start) },
    { "where", "Portable",
      _emb_pte_portable__where_start, static_cast<std::size_t>(_emb_pte_portable__where_end - _emb_pte_portable__where_start) },
    { "dequantize_per_tensor", "Cortex-M",
      _emb_pte_cortex_m__dequantize_per_tensor_start, static_cast<std::size_t>(_emb_pte_cortex_m__dequantize_per_tensor_end - _emb_pte_cortex_m__dequantize_per_tensor_start) },
    { "maximum", "Cortex-M",
      _emb_pte_cortex_m__maximum_start, static_cast<std::size_t>(_emb_pte_cortex_m__maximum_end - _emb_pte_cortex_m__maximum_start) },
    { "minimum", "Cortex-M",
      _emb_pte_cortex_m__minimum_start, static_cast<std::size_t>(_emb_pte_cortex_m__minimum_end - _emb_pte_cortex_m__minimum_start) },
    { "pad", "Cortex-M",
      _emb_pte_cortex_m__pad_start, static_cast<std::size_t>(_emb_pte_cortex_m__pad_end - _emb_pte_cortex_m__pad_start) },
    { "quantize_per_tensor", "Cortex-M",
      _emb_pte_cortex_m__quantize_per_tensor_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantize_per_tensor_end - _emb_pte_cortex_m__quantize_per_tensor_start) },
    { "quantized_add", "Cortex-M",
      _emb_pte_cortex_m__quantized_add_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_add_end - _emb_pte_cortex_m__quantized_add_start) },
    { "quantized_avg_pool2d", "Cortex-M",
      _emb_pte_cortex_m__quantized_avg_pool2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_avg_pool2d_end - _emb_pte_cortex_m__quantized_avg_pool2d_start) },
    { "quantized_batch_matmul", "Cortex-M",
      _emb_pte_cortex_m__quantized_batch_matmul_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_batch_matmul_end - _emb_pte_cortex_m__quantized_batch_matmul_start) },
    { "quantized_conv2d", "Cortex-M",
      _emb_pte_cortex_m__quantized_conv2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_conv2d_end - _emb_pte_cortex_m__quantized_conv2d_start) },
    { "quantized_depthwise_conv2d", "Cortex-M",
      _emb_pte_cortex_m__quantized_depthwise_conv2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_depthwise_conv2d_end - _emb_pte_cortex_m__quantized_depthwise_conv2d_start) },
    { "quantized_linear", "Cortex-M",
      _emb_pte_cortex_m__quantized_linear_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_linear_end - _emb_pte_cortex_m__quantized_linear_start) },
    { "quantized_max_pool2d", "Cortex-M",
      _emb_pte_cortex_m__quantized_max_pool2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_max_pool2d_end - _emb_pte_cortex_m__quantized_max_pool2d_start) },
    { "quantized_mul", "Cortex-M",
      _emb_pte_cortex_m__quantized_mul_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_mul_end - _emb_pte_cortex_m__quantized_mul_start) },
    { "quantized_transpose_conv2d", "Cortex-M",
      _emb_pte_cortex_m__quantized_transpose_conv2d_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_transpose_conv2d_end - _emb_pte_cortex_m__quantized_transpose_conv2d_start) },
    { "softmax", "Cortex-M",
      _emb_pte_cortex_m__softmax_start, static_cast<std::size_t>(_emb_pte_cortex_m__softmax_end - _emb_pte_cortex_m__softmax_start) },
    { "transpose", "Cortex-M",
      _emb_pte_cortex_m__transpose_start, static_cast<std::size_t>(_emb_pte_cortex_m__transpose_end - _emb_pte_cortex_m__transpose_start) },
    { "quantized_depthwise_conv2d_deep", "Cortex-M",
      _emb_pte_cortex_m__quantized_depthwise_conv2d_deep_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_depthwise_conv2d_deep_end - _emb_pte_cortex_m__quantized_depthwise_conv2d_deep_start) },
    { "quantized_conv2d_1xn_pad", "Cortex-M",
      _emb_pte_cortex_m__quantized_conv2d_1xn_pad_start, static_cast<std::size_t>(_emb_pte_cortex_m__quantized_conv2d_1xn_pad_end - _emb_pte_cortex_m__quantized_conv2d_1xn_pad_start) },
};

const std::size_t g_embedded_models_count = sizeof(g_embedded_models) / sizeof(g_embedded_models[0]);
